### ISSUE TITLE
Error when building Master's Console - unknown block type minecraft:sign

### ISSUE THREAD

**Issue by VintageGnu** [eccentricdevotion/TARDIS#104]
Spigot: 1.14.1
TARDIS: 1853
TARDIS ChunkGen: 61

There are errors being generated in the server log when attempting to switch to the Master's Console. These will just keep generating a couple of times a second until the server is restarted.

Error Log:

```
[19:02:26] [Server thread/WARN]: [TARDIS] Task #16498 for TARDIS v4.1.0-b1853 generated an exception
java.lang.IllegalArgumentException: Could not parse data: minecraft:sign[rotation=6,waterlogged=false]
	at org.bukkit.craftbukkit.v1_14_R1.block.data.CraftBlockData.newData(CraftBlockData.java:531) ~[spigot.jar:git-Spigot-03bd4b0-342194e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createBlockData(CraftServer.java:1849) ~[spigot.jar:git-Spigot-03bd4b0-342194e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createBlockData(CraftServer.java:1842) ~[spigot.jar:git-Spigot-03bd4b0-342194e]
	at me.eccentric_nz.TARDIS.desktop.TARDISFullThemeRunnable.run(TARDISFullThemeRunnable.java:415) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-03bd4b0-342194e]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-03bd4b0-342194e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot.jar:git-Spigot-03bd4b0-342194e]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-03bd4b0-342194e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot.jar:git-Spigot-03bd4b0-342194e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot.jar:git-Spigot-03bd4b0-342194e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:sign' at position 0: <--[HERE]
```

**Comment by eccentricdevotion** [comment]
What theme/console were you trying to change to?

**Comment by eccentricdevotion** [comment]
Fixed in build 1854
1efc996

**Comment by ZurielLarios** [comment]
how do u fix that? im the same problem :c

**Comment by eccentricdevotion** [comment]
> how do u fix that? im the same problem :c

Update the plugin

**Comment by eccentricdevotion** [comment]
> no, I mean i have a similar problem in my mod and idk how to resolve it :c

Edit or remake your schematic file - change any instances of `minecraft:sign` and change them to `minecraft:oak_sign`

**Comment by ZurielLarios** [comment]
thx, i'll try
