### ISSUE TITLE
NoSuchMethodError in bee wakeup task

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#192]
```
INFO java.lang.NoSuchMethodError: org.bukkit.block.Beehive.releaseEntities()Ljava/util/List;
INFO at me.eccentric_nz.TARDIS.mobfarming.TARDISBeeWaker.wakeBees(TARDISBeeWaker.java:66) ~[?:?]
INFO at me.eccentric_nz.TARDIS.mobfarming.TARDISBeeWaker.run(TARDISBeeWaker.java:44) ~[?:?]
INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-93]
INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-93]
INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-93]
INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-93]
INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-93]
INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-93]
INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
Server version: `Paper version git-Paper-93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
TARDIS version: build 1993 (I just got the update notification, I'm updating now, but I don't know if this has been fixed since)

**Comment by eccentricdevotion** [comment]
As noted on the commit, you need to update Paper/Spigot

**Comment by PrincessRTFM** [comment]
Guess I have to wait for my server host to catch up...
