### ISSUE TITLE
[CRITICAL] Cannot exit Time Vortex when location is set after entering

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#209]
**Describe the bug**
I disengaged the handbrake, but apparently forgot to set my destination first. While the engines cycled, I set my destination, but the TARDIS wouldn't materialise. I checked the console and found an error.

**To Reproduce**
Do not set a destination. Disengage the handbrake. Wait until the engines start cycling. Set a destination.

**Log files**
```
This server is running Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```
```
14.02 08:46:40 [Server] ERROR Could not pass event PlayerInteractEvent to TARDIS v4.3-b2001
14.02 08:46:40 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tardistravel' in plugin TARDIS v4.3-b2001
14.02 08:46:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:458) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at me.eccentric_nz.TARDIS.listeners.TARDISBindListener.onInteract(TARDISBindListener.java:228) ~[?:?]
14.02 08:46:40 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor339.execute(Unknown Source) ~[?:?]
14.02 08:46:40 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1374) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
14.02 08:46:40 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
14.02 08:46:40 [Server] INFO at me.eccentric_nz.TARDIS.utility.TARDISStaticLocationGetters.getLocationFromBukkitString(TARDISStaticLocationGetters.java:91) ~[?:?]
14.02 08:46:40 [Server] INFO at me.eccentric_nz.TARDIS.flight.TARDISLand.exitVortex(TARDISLand.java:49) ~[?:?]
14.02 08:46:40 [Server] INFO at me.eccentric_nz.TARDIS.commands.TARDISTravelCommands.onCommand(TARDISTravelCommands.java:650) ~[?:?]
14.02 08:46:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-102]
14.02 08:46:40 [Server] INFO ... 25 more
```

**Comment by eccentricdevotion** [comment]
How did you set the destination?

**Comment by PrincessRTFM** [comment]
Handbrake location was not set recently. Destination was set via bound sign. Using the `save-sign` to set the destination also failed to materialise.

**Comment by eccentricdevotion** [comment]
Error points to the stored handbrake location not being valid...

**Comment by PrincessRTFM** [comment]
I haven't changed it since at least a week back, I right-clicked to disengage it without issue, and when left-clicking it I get the message about not doing that while in the vortex. I set the _secondary_ handbrake's location a day or so ago, after the update that redid the whole secondary controls system, could that be related?

**Comment by eccentricdevotion** [comment]
Maybe

**Comment by PrincessRTFM** [comment]
I can upload my `TARDIS.db` file if that would help?

**Comment by PrincessRTFM** [comment]
Apparently github doesn't like `.db` files, but `.zip` are fine. Anyway, I'm about to pass out from not _nearly_ enough sleep, so here's [my TARDIS.db file but zipped up](https://github.com/eccentricdevotion/TARDIS/files/4204217/TARDIS.db.zip), hope that helps

**Comment by eccentricdevotion** [comment]
You'll need to update your secondary handbrake, but should be fixed in build 2002

**Comment by PrincessRTFM** [comment]
Sorry, just checking - I'm still tired - do you mean I need to do the `/tardis secondary handbrake` and click thing, then select my destination, then I'll leave the Vortex and can park?

**Comment by PrincessRTFM** [comment]
Yep, finally got on to try it, that worked!
