### ISSUE TITLE
Condenser no longer works

### ISSUE THREAD

**Issue by mystical1** [eccentricdevotion/TARDIS#218]
Condenser was working fine and I have no clue what happened.
No blocks are being recognized.
This the error on the console 

```
[15:53:09] [Server thread/INFO]: [DiscordSRV] Player Mystical1 joined with silent joining permission, not sending a join message
[15:53:09] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TARDIS v4.3-b2014
org.bukkit.event.EventException: null
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.listeners.TARDISJoinListener.onJoin(TARDISJoinListener.java:176) ~[?:?]
```

```
[15:53:43] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to TARDIS v4.3-b2014
org.bukkit.event.EventException: null
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.artron.TARDISCondenserListener.onChestClose(TARDISCondenserListener.java:131) ~[?:?]
```

**Comment by eccentricdevotion** [comment]
Error points to the plugin not being loaded properly. Something is preventing the plugin from loading what it needs to function, in this case the list of condensable blocks.

**Comment by eccentricdevotion** [comment]
Check for enable errors further back in the log.

You still have the _TARDIS_TimeVortex_ world being managed by Multiverse...

**Comment by mystical1** [comment]
I did /mvunload and restarted the server  but after the reboot it was still listed under /mv list. 
This is the enable errors.

[21:43:15] [Server thread/INFO]: [0;33;22m[TARDIS][m Loaded 2 portals.[m
[21:43:15] [Server thread/INFO]: [0;33;22m[TARDIS][m Loaded 0 TARDISes in Siege Mode.[m
[21:43:15] [Server thread/INFO]: [0;33;22m[TARDIS][m Loaded 0 dispersed Police Boxes.[m
[21:43:15] [Server thread/ERROR]: Error occurred while enabling TARDIS v4.3-b2016 (Is it up to date?)
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_221]
	at me.eccentric_nz.TARDIS.JSON.JSONTokener.<init>(JSONTokener.java:76) ~[?:?]
	at me.eccentric_nz.TARDIS.JSON.JSONArray.<init>(JSONArray.java:136) ~[?:?]
	at me.eccentric_nz.TARDIS.chameleon.TARDISConstructColumn.getColumn(TARDISConstructColumn.java:50) ~[?:?]
	at me.eccentric_nz.TARDIS.builders.TARDISInstaPreset.buildPreset(TARDISInstaPreset.java:88) ~[?:?]
	at me.eccentric_nz.TARDIS.flight.TARDISVortexPersister.load(TARDISVortexPersister.java:142) ~[?:?]
	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:350) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

If you want the complete log then let me know.

**Comment by mystical1** [comment]
Oh I forgot to say Thank you . 
Thank you !

**Comment by eccentricdevotion** [comment]
You want `mv remove TARDIS_TimeVortex`, unload is only temporary.

Someone has their TARDIS exterior set to a custom CONSTRUCT, but the plugin can't actually find the construct data in the database so it is preventing the plugin from loading. You'll probably need to edit the database and change the player's chameleon presets to FACTORY.

This has possibly happened because they tried to build a construct with a new 1.15.x block and it looks like I haven't added them to the construct code...

**Comment by eccentricdevotion** [comment]
176315f
Build 2017

**Comment by mystical1** [comment]
Since I am not a techy person I have no clue which part I have to edit. Any pointers on what I should be looking for would be gratefully appreciated. Thanks

**Comment by eccentricdevotion** [comment]
I use SQLite Browser https://sqlitebrowser.org/dl/ to view and edit the TARDIS.db

1. Open up the database
2. Switch to Browse Data tab
3. Select the `tardis` table
4. Find any tardis records where the `chameleon_preset` or `chameleon_demat` columns = CONSTRUCT
5. Change the records to FACTORY
6. Write database changes
7. Close file

![dbbrowser](https://user-images.githubusercontent.com/1841924/75082716-dd465800-5579-11ea-9044-7d4d63198eaf.png)

**Comment by eccentricdevotion** [comment]
Have made some changes in build 2024 that my help with this.
