### ISSUE TITLE
Cannot /tardisgive [me] seed [invalid_seed] returns nothing

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#248]
Not sure why, am I misconfigured or something?

Also, nothing gets returned if you do `/tgive [me] seed [non-existent seed]`. 

<details>
<summary>Stack Trace</summary>

```
org.bukkit.command.CommandException: Unhandled exception executing command 'tgive' in plugin TARDIS v4.3-b2063
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.custommodeldata.TARDISSeedModel.modelByString(TARDISSeedModel.java:113) ~[?:?]
	at me.eccentric_nz.TARDIS.commands.admin.TARDISGiveCommand.giveSeed(TARDISGiveCommand.java:371) ~[?:?]
	at me.eccentric_nz.TARDIS.commands.admin.TARDISGiveCommand.onCommand(TARDISGiveCommand.java:172) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
	... 17 more
```
</details>

**Comment by PrincessRTFM** [comment]
```
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.custommodeldata.TARDISSeedModel.modelByString(TARDISSeedModel.java:113) ~[?:?]
```

...what in the _fuck_? I just pulled up [the line in question](https://github.com/eccentricdevotion/TARDIS/blob/8f0876836b9f553cc9b578ebf010c7ac341e22a3/src/main/java/me/eccentric_nz/TARDIS/custommodeldata/TARDISSeedModel.java#L113), and it makes no sense for there to be an NPE there. The only thing I can find that _could_ be causing it is if `consoleMap` is `null`, but it's statically declared on class initialisation at [line 80](https://github.com/eccentricdevotion/TARDIS/blob/8f0876836b9f553cc9b578ebf010c7ac341e22a3/src/main/java/me/eccentric_nz/TARDIS/custommodeldata/TARDISSeedModel.java#L80).

**Comment by Chew** [comment]
Could mean that seed doesn't exist even though it's a valid console or vice versa

**Comment by PrincessRTFM** [comment]
But `HashMap.get()` returns `null` if there's no value for the requested key, it doesn't throw. And the trace says the error is being _thrown_ at line 113. That means something's trying to call a method on `null`, and the only thing any method is being called on at line 113 is `consoleMap`. If it just returned `null`, then at _worst_ there'd be an NPE somewhere _else_, where the return value is being used, assuming ED doesn't do a null check, which I'd expect he does.

**Comment by eccentricdevotion** [comment]
There are no seeds for small/medium/tall - they're templates only used by the Desktop Theme GUI.
`TARDISSeedModel.modelByString(String str)` is returning a NPE because `TARDISSeedModel.modelByString("TALL")` is not a valid key for the `consoleMap` map.

> Also, nothing gets returned if you do `/tgive [me] seed [non-existent seed]`.

This is what I need to fix.

**Comment by PrincessRTFM** [comment]
> `TARDISSeedModel.modelByString(String str)` is returning a NPE because `TARDISSeedModel.modelByString("TALL")` is not a valid key for the `consoleMap` map.

But the docs for `HashMap.get()` say it only _returns_ `null`, nothing about throwing an exception... and the error is coming from the `.get()` call.

I'm so confused.

You seem to know what you're doing, so just ignore me.

**Comment by eccentricdevotion** [comment]
> I'm so confused.

The `caused by` line (in the stack trace) is showing where the null value is coming from, not what is throwing the NPE

**Comment by PrincessRTFM** [comment]
Since when has it done that? I must be really behind on my java...

**Comment by eccentricdevotion** [comment]
Yeah, this one is actually a little weird, as the NPE probably isn't thrown until it is unboxed on line 375 (or [398](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/commands/admin/TARDISGiveCommand.java#L398) in the current code)
