### ISSUE TITLE
Could not pass event InventoryClickEvent to TARDIS when clicking Nether world in Destination Terminal

### ISSUE THREAD

**Issue by Technoguyfication** [eccentricdevotion/TARDIS#254]
**Describe the bug**
Exception: Could not pass event InventoryClickEvent to TARDIS v4.3-b2067

I have tried setting `travel.nether: true` in config.yml, and `planets.world_nether: true` in planets.yml to no effect. This bug is apparent on the zipped copy of the server I sent you in #220 if you still have that saved.

**Version: TARDIS version: 4.3-b2066 with CraftBukkit git-Paper-182 (MC: 1.15.2)**

**To Reproduce**
1. Open destination terminal
2. Click netherrack world to travel to nether
3. Exception happens in console

**Screenshots**
![](https://tkno.pw/2XBcZxB)

The world name lore text never pops up when clicking the world and the exception appears each time you click the netherrack

**Log files**
```[18:36:28 ERROR]: Could not pass event InventoryClickEvent to TARDIS v4.3-b2067
java.lang.NullPointerException: null
        at me.eccentric_nz.TARDIS.travel.TARDISTerminalListener.getWorld(TARDISTerminalListener.java:426) ~[?:?]
        at me.eccentric_nz.TARDIS.travel.TARDISTerminalListener.setCurrent(TARDISTerminalListener.java:355) ~[?:?]
        at me.eccentric_nz.TARDIS.travel.TARDISTerminalListener.onDestTerminalClick(TARDISTerminalListener.java:134) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor297.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-182]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-182]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-182]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2333) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1052) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1022) ~[patched_1.15.2.jar:git-Paper-182]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:945) ~[patched_1.15.2.jar:git-Paper-182]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]```

**Comment by eccentricdevotion** [comment]
In _planets.yml_ it should be:
```
planets:
   world_nether:
      enabled: false // will be loaded by the server
      time_travel: true
```
You can toggle world inclusion for travelling with the `/tadmin [include|exclude] [world]` command, no need to manually edit the planets config.

**Comment by Chew** [comment]
I actually have this too.
If I click the dirt block (World selector), then the nether works. I have to click the dirt/grass first otherwise it'll return that error. Only the first time though, it's weird.

**Comment by eccentricdevotion** [comment]
Will have a play after work

**Comment by eccentricdevotion** [comment]
Fixed
Build 2070
