### ISSUE TITLE
[1.16.1] Equipping Perception Filter in CREATIVE crashes the server

### ISSUE THREAD

**Issue by Exeloo** [eccentricdevotion/TARDIS#293]
In some condition, Tardis plugin shut down the server

When you are in gm 1 and you do a right click with the perception filter, 

![2020-06-25_17 36 33](https://user-images.githubusercontent.com/67429441/85751542-f8cd9500-b70a-11ea-8e90-9f2f94954a30.png)
![2020-06-25_17 36 44](https://user-images.githubusercontent.com/67429441/85751621-05ea8400-b70b-11ea-8c2b-e94c2ec91709.png)
![Capture](https://user-images.githubusercontent.com/67429441/85752039-5d88ef80-b70b-11ea-8a7a-0c832d722a0b.JPG)

```
[17:36:02] [Server thread/INFO]: Exelo_ issued server command: /gamemode creative
[17:36:02] [Server thread/INFO]: [Exelo_: Set own game mode to Creative Mode]
[17:36:36] [Server thread/INFO]: Exelo_ issued server command: /tardisgive Exelo_ filter 1
[17:36:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:99) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:884) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:407) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1352) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[17:36:56] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Exelo\Desktop\Prg\Minecraft\Plugin\LocalHost\LocalHost 1.16.1\.\crash-reports\crash-2020-06-25_17.36.56-server.txt
[17:36:56] [Server thread/INFO]: Stopping server
[17:36:56] [Server thread/INFO]: [TARDIS] Disabling TARDIS v4.4.4-b2153
[17:36:56] [Server thread/INFO]: [TARDIS] Saved 0 dispersed TARDISes.
[17:36:56] [Server thread/INFO]: [TARDIS] Saved 0 TARDISes floating around in the time vortex.
[17:36:56] [Server thread/INFO]: [TARDISChunkGenerator] Disabling TARDISChunkGenerator v4.4.4
[17:36:56] [Server thread/INFO]: Saving players
[17:36:56] [Server thread/INFO]: Exelo_ lost connection: Server closed
[17:36:56] [Server thread/INFO]: Exelo_ left the game
[17:36:56] [Server thread/INFO]: Saving worlds
[17:36:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[17:37:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:37:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[17:37:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:37:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[17:37:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:37:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[TARDIS_TimeVortex]'/minecraft:tardis_timevortex
[17:37:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (TARDIS_TimeVortex): All chunks are saved
[17:37:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:37:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:37:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:37:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (TARDIS_TimeVortex): All chunks are saved
```
Crash Report:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 25/06/20 17:36
Description: Exception in server tick loop

java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:99)
	at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:884)
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:407)
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1352)
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941)
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918)
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850)
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 188660928 bytes (179 MB) / 661291008 bytes (630 MB) up to 1037959168 bytes (989 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms512M -Xmx1024M
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) true
   Plugins: { TARDISChunkGenerator v4.4.4 me.eccentric_nz.tardischunkgenerator.TARDISHelper [eccentric_nz], TARDIS v4.4.4-b2153 me.eccentric_nz.TARDIS.TARDIS [eccentric_nz],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING Worker-Main-11: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING TimerQueue: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.DelayQueue.take(Unknown Source), javax.swing.TimerQueue.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], WAITING Worker-Main-24: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], RUNNABLE Signal Dispatcher: [], TIMED_WAITING mysql-cj-abandoned-connection-cleanup: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:80), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], RUNNABLE Attach Listener: [], WAITING AWT-Shutdown: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), sun.awt.AWTAutoShutdown.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #2: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer hack thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_16_R1.SystemUtils$2.run(SourceFile:524)], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Unknown Source)], RUNNABLE TerminalConsoleWriter: [java.io.FileOutputStream.writeBytes(Native Method), java.io.FileOutputStream.write(Unknown Source), java.io.BufferedOutputStream.flushBuffer(Unknown Source), java.io.BufferedOutputStream.flush(Unknown Source), java.io.PrintStream.flush(Unknown Source), java.io.FilterOutputStream.flush(Unknown Source), java.io.PrintStream.flush(Unknown Source), java.io.PrintStream.flush(Unknown Source), java.io.FilterOutputStream.flush(Unknown Source), sun.nio.cs.StreamEncoder.implFlush(Unknown Source), sun.nio.cs.StreamEncoder.flush(Unknown Source), java.io.OutputStreamWriter.flush(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.flush(ConsoleReader.java:976), org.bukkit.craftbukkit.v1_16_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:39)], TIMED_WAITING Craft Scheduler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Worker-Bootstrap-7: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE AWT-EventQueue-0: [javax.swing.text.PlainView.updateMetrics(Unknown Source), javax.swing.text.PlainView.updateDamage(Unknown Source), javax.swing.text.PlainView.insertUpdate(Unknown Source), javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(Unknown Source), javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(Unknown Source), javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source), javax.swing.text.AbstractDocument.handleInsertString(Unknown Source), javax.swing.text.AbstractDocument.insertString(Unknown Source), javax.swing.text.PlainDocument.insertString(Unknown Source), net.minecraft.server.v1_16_R1.ServerGUI.a(ServerGUI.java:177), net.minecraft.server.v1_16_R1.ServerGUI.lambda$5(ServerGUI.java:165), net.minecraft.server.v1_16_R1.ServerGUI$$Lambda$2972/9724961.run(Unknown Source), java.awt.event.InvocationEvent.dispatch(Unknown Source), java.awt.EventQueue.dispatchEventImpl(Unknown Source), java.awt.EventQueue.access$500(Unknown Source), java.awt.EventQueue$3.run(Unknown Source), java.awt.EventQueue$3.run(Unknown Source), java.security.AccessController.doPrivileged(Native Method), java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source), java.awt.EventQueue.dispatchEvent(Unknown Source), java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source), java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source), java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source), java.awt.EventDispatchThread.pumpEvents(Unknown Source), java.awt.EventDispatchThread.pumpEvents(Unknown Source), java.awt.EventDispatchThread.run(Unknown Source)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-4-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), sun.java2d.Disposer.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING IO-Worker-20: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING IO-Worker-18: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), net.minecraft.server.v1_16_R1.ServerGUI.lambda$3(ServerGUI.java:136), net.minecraft.server.v1_16_R1.ServerGUI$$Lambda$2964/13015075.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_16_R1.CraftCrashReport.call(CraftCrashReport.java:33), net.minecraft.server.v1_16_R1.CrashReportSystemDetails.a(SourceFile:79), net.minecraft.server.v1_16_R1.CrashReport.i(CrashReport.java:71), net.minecraft.server.v1_16_R1.CrashReport.<init>(CrashReport.java:35), net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:872), net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164), net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2951/12559552.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], TIMED_WAITING IO-Worker-21: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE AWT-Windows: [sun.awt.windows.WToolkit.eventLoop(Native Method), sun.awt.windows.WToolkit.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:102)], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:215), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.access$000(WindowsTerminal.java:55), org.bukkit.craftbukkit.libs.jline.WindowsTerminal$1.read(WindowsTerminal.java:157), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349), net.minecraft.server.v1_16_R1.DedicatedServer$1.run(DedicatedServer.java:81)],}
   Recent tasks from 1728-1758{TARDIS:me.eccentric_nz.TARDIS.database.TARDISRecordingTask@1760,TARDIS:me.eccentric_nz.TARDIS.database.TARDISRecordingTask@1765,TARDIS:me.eccentric_nz.TARDIS.database.TARDISRecordingTask@1770,TARDIS:me.eccentric_nz.TARDIS.database.TARDISRecordingTask@1775,TARDIS:me.eccentric_nz.TARDIS.database.TARDISRecordingTask@1780,TARDIS:me.eccentric_nz.TARDIS.database.TARDISRecordingTask@1785,}
   Force Loaded Chunks: { world: {}, world_nether: {}, world_the_end: {}, TARDIS_TimeVortex: {},}
	Player Count: 1 / 20; [EntityPlayer['Exelo_'/245, l='ServerLevel[world]', x=-73.50, y=76.00, z=67.49](Exelo_ at -73.4996927521134,76.0,67.48548816528294)]
	Data Packs: vanilla, file/tardis (incompatible)
	Is Modded: Definitely; Server brand changed to 'Spigot'
	Type: Dedicated Server (map_server.txt)
```
the Tardis version is #2153

**Comment by Chew** [comment]
Can confirm this happens on Latest Spigot (git-Spigot-758abbe-3f0c333 (MC: 1.16.1)), Latest TARDIS (b2153), Latest TARDISChunkGenerator (b99).

**Comment by eccentricdevotion** [comment]
Does it do the same thing in 1.15.2?

**Comment by Chew** [comment]
Build 2153 doesn't even boot in 1.15.2
```
[15:28:55 ERROR]: Could not load 'plugins/TARDISChunkGenerator-b99.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/IChatBaseComponent
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/IChatBaseComponent
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-372]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R1.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-372]
	... 6 more
[15:28:55 ERROR]: Could not load 'plugins/TARDIS-b2153.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency TARDISChunkGenerator. Please download and install TARDISChunkGenerator to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:832) [?:?]```

**Comment by eccentricdevotion** [comment]
No, I wouldn't expect it to. You'd have to test a previous 1.15.2 compatible build.
Just trying to determine whether its an existing bug, or has been introduced with 1.16.1

**Comment by Chew** [comment]
Works fine on latest Paper (b372), TARDIS b2152 and TCG b98

**Comment by eccentricdevotion** [comment]
Thanks for checking.
Would seem to be a change in 1.16.1, you can't set the item in hand to AIR or null when in creative.
I'll push a temporary fix until I can investigate further.

**Comment by eccentricdevotion** [comment]
Unresolved bug in Spigot
https://hub.spigotmc.org/jira/browse/SPIGOT-3020

**Comment by Chew** [comment]
This seems to be a recurring theme with plugins... spigot side not plugin side lol

**Comment by Chew** [comment]
Interestingly, the bug on the initial b2153 on latest Paper didn't crash at all. Definitely a Spigot bug Paper already patched. Doesn't crash on latest Spigot or latest Paper with latest builds
