### ISSUE TITLE
TARDIS is not landing on certain worlds, throws an error

### ISSUE THREAD

**Issue by IvIurdoc** [eccentricdevotion/TARDIS#360]
Hey there, the TARDIS is having trouble landing on certain planets in my server. These worlds aren't much different than other worlds, besides the fact that they are pregenerated worlds using custom datapack generation from 1.16.2, and then the datapacks are removed, leaving behind just the custom generation. It seems that the TARDIS won't land on these planets, why is this?

>.... [00:21:37 INFO]: [TARDIS] Server version: git-Paper-174 (MC: 1.16.2)
>.... [00:21:37 INFO]: [TARDIS] TARDIS version: 4.5-b2190
>.... [00:21:37 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
>.... [00:21:37 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
>.... [00:21:37 INFO]: [TARDIS] LibsDisguises version: 10.0.16
>.... [00:21:37 INFO]: [TARDIS] Essentials version: 2.18.1.0
>.... [00:21:37 INFO]: [TARDIS] WorldBorder version: 1.9.10 (beta)
>.... [00:21:37 INFO]: [TARDIS] WorldGuard version: 7.0.4-SNAPSHOT+2067-91a1494
>.... [00:21:37 INFO]: [TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-b787
>.... [00:21:37 INFO]: [TARDIS] LockettePro version: 2.9.10-1.15.1
>.... [00:21:37 INFO]: [TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-b476
>.... [00:21:37 INFO]: [TARDIS] Towny version: 0.96.2.0
>.... [00:21:37 INFO]: [TARDIS] Checking for new TARDIS builds...

<details>
  <summary>Server log</summary>

```
.... [00:17:28 WARN]: [TARDIS] Task #93282 for TARDIS v4.5-b2190 generated an exception
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_16_R2.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.2.jar:git-Paper-174]
at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:516) ~[patched_1.16.2.jar:git-Paper-174]
at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.getBiome(CraftWorld.java:1087) ~[patched_1.16.2.jar:git-Paper-174]
at me.eccentric_nz.TARDIS.builders.TARDISPresetBuilderFactory.buildPreset(TARDISPresetBuilderFactory.java:98) ~[?:?]
at me.eccentric_nz.TARDIS.flight.TARDISMaterialseFromVortex.lambda$run$3(TARDISMaterialseFromVortex.java:236) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-174]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-174]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-174]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-174]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-174]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-174]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-174]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

</details>

**Comment by IvIurdoc** [comment]
>.... [01:22:44 WARN]: [TARDIS] Task #157182 for TARDIS v4.5-b2190 generated an exception
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_16_R2.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.2.jar:git-Paper-175]
at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:516) ~[patched_1.16.2.jar:git-Paper-175]
at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.getBiome(CraftWorld.java:1087) ~[patched_1.16.2.jar:git-Paper-175]
at me.eccentric_nz.TARDIS.builders.TARDISPresetBuilderFactory.buildPreset(TARDISPresetBuilderFactory.java:98) ~[?:?]
at me.eccentric_nz.TARDIS.flight.TARDISMaterialseFromVortex.lambda$run$3(TARDISMaterialseFromVortex.java:236) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-175]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-175]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-175]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-175]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-175]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-175]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-175]

throws this error every time

**Comment by eccentricdevotion** [comment]
Spigot doesn't support custom biomes... Minecraft server will load them, but plugins can't interact with them.
As soon as support is added to Spigot, TARDIS will be updated.
https://hub.spigotmc.org/jira/browse/SPIGOT-6073

**Comment by IvIurdoc** [comment]
That's not the problem, these aren't listed as custom worlds anymore, they're normal worlds now. It's like using a spigot world generator, pregenerating the world, and then removing the generator. There's no datapacks or anything involved anymore..

**Comment by IvIurdoc** [comment]
The biome reverts back to Ocean for these planets, and the generation remains - there are no custom biomes.

**Comment by eccentricdevotion** [comment]
Did you even read the error that you are repeatedly getting? Let's step through it from when TARDIS tries to land in the world:

> `me.eccentric_nz.TARDIS.builders.TARDISPresetBuilderFactory.buildPreset(TARDISPresetBuilderFactory.java:98) ~[?:?]`

This line points to line [98 in TARDISPresetBuilderFactory](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/builders/TARDISPresetBuilderFactory.java#L98), which gives us this:

> `biome = bd.getLocation().getWorld().getBiome(bd.getLocation().getBlockX(), bd.getLocation().getBlockY(), bd.getLocation().getBlockZ());`

TARDIS makes a call to `World#getBiome()`, for now ignore the fact that TARDIS is making the call, _this could be any Spigot plugin_

The next few lines trace the `getBiome()` call

> `at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.getBiome(CraftWorld.java:1087) ~[patched_1.16.2.jar:git-Paper-175]`
> `at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:516) ~[patched_1.16.2.jar:git-Paper-175]`
> `at org.bukkit.craftbukkit.v1_16_R2.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.2.jar:git-Paper-175]`

Which results in a null pointer exception

> `java.lang.NullPointerException: null`

This is CraftBukkit (Spigot) throwing the error - not TARDIS - TARDIS is just calling a Spigot API method - therefore the information that is stored in the Minecraft world - regardless of whether the datapack has been removed or not - still references a custom biome that Spigot doesn't know how to handle.

Until Spigot adds support for custom biomes / dimensions from datapacks, there is nothing that TARDIS can do about it, that `getBiome()` call will always throw the error if the [biome is not in the list of vanilla biomes](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html).

**Comment by eccentricdevotion** [comment]
Coded a fix, but it's not perfect.
Best to travel to custom worlds with a preset that **won't try to set the biome** at the TARDIS exterior location so that Optifine Police Box textures work (the presets are the `NEW` & `OLD` blue police boxes, all the rest should be fine). The plugin will still set the biome (to `DEEP_OCEAN`), but at this moment in time it is impossible to restore the custom biome back when the TARDIS leaves.
