### ISSUE TITLE
TARDISes get stuck in custom worlds, once custom world was removed from server the TARDIS remains stuck, throws different error.

### ISSUE THREAD

**Issue by TuckerAndrews3** [eccentricdevotion/TARDIS#364]
So I know I've posted here before about TARDISes not being able to land in custom worlds, and I understand that bug couldn't be fixed, but we've encountered a new bug where they straight up break and won't let you call them or land them or anything like that when they try to land on one. I've removed the custom world and cleared the vortex table in hopes that these people would be able to land their TARDISes and use them again but it throws this error, it tells you the whole "internal error" spiel when you run it.

```
> .... [15:23:41 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'tardis' in plugin TARDIS v4.5.2-b2193
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-195]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-195]
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-195]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
> Caused by: java.lang.IllegalArgumentException: Invalid namespace. Must be [a-z0-9._-]: TARDISBiome{key=minecraft
> at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.3.jar:git-Paper-195]
> at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[patched_1.16.3.jar:git-Paper-195]
> at me.eccentric_nz.TARDIS.database.ResultSetCurrentLocation.resultSet(ResultSetCurrentLocation.java:112) ~[?:?]
> at me.eccentric_nz.TARDIS.commands.tardis.TARDISComehereCommand.doComeHere(TARDISComehereCommand.java:139) ~[?:?]
> at me.eccentric_nz.TARDIS.commands.tardis.TARDISCommands.onCommand(TARDISCommands.java:121) ~[?:?]
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-195]
> ... 18 more
```

The custom worlds were basically our way of cheating them in.. we would pregen them using the datapack and then remove the datapack and put a worldborder on the world, this actually worked but it causes issues with TARDIS so we've decided to remove these worlds.. now that they don't exist, the TARDISes that had problems landing on them still throw errors. So that makes me wonder if the bug could be fix and the worlds could be loaded back in.. not sure, but still, we need to find a way to fix this.

```
> >....=>.... [15:27:15 INFO]: [TARDIS] Server version: git-Paper-195 (MC: 1.16.3)
> >.... [15:27:15 INFO]: [TARDIS] TARDIS version: 4.5.2-b2193
> >.... [15:27:15 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5.2
> >.... [15:27:15 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
> >.... [15:27:15 INFO]: [TARDIS] LibsDisguises version: 10.0.16
> >.... [15:27:15 INFO]: [TARDIS] Essentials version: 2.18.1.9
> >.... [15:27:15 INFO]: [TARDIS] WorldBorder version: 2.0.9
> >.... [15:27:15 INFO]: [TARDIS] WorldGuard version: 7.0.4-SNAPSHOT+2069-c860fce
> >.... [15:27:15 INFO]: [TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-b789
> >.... [15:27:15 INFO]: [TARDIS] LockettePro version: 2.9.10-1.15.1
> >.... [15:27:15 INFO]: [TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-b477
> >.... [15:27:15 INFO]: [TARDIS] Towny version: 0.96.2.0
> >.... [15:27:15 INFO]: [TARDIS] Checking for new TARDIS builds...
```

This error is popping up too, and I know it's related, but I don't know what exactly is causing it or what it means

```
> >.... [15:25:18 ERROR]: Could not pass event InventoryClickEvent to TARDIS v4.5.2-b2193
> java.lang.IllegalArgumentException: Invalid namespace. Must be [a-z0-9._-]: TARDISBiome{key=minecraft
> at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.3.jar:git-Paper-195]
> at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[patched_1.16.3.jar:git-Paper-195]
> at me.eccentric_nz.TARDIS.database.ResultSetCurrentLocation.resultSet(ResultSetCurrentLocation.java:112) ~[?:?]
> at me.eccentric_nz.TARDIS.listeners.TARDISSaveSignListener.onSaveTerminalClick(TARDISSaveSignListener.java:129) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1162.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-195]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-195]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-195]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-195]
> at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-195]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by eccentricdevotion** [comment]
Attach your TARDIS.db file

It looks like there are issues with the biome namespace for some saved TARDIS locations, I'll need to see what the values are in your database file.

**Comment by eccentricdevotion** [comment]
And TARDIS can now land in custom worlds/biomes made from data packs, at least the ones I've tested with.

**Comment by eccentricdevotion** [comment]
Removing worlds when there ate still references to them in the TARDIS database is not really a good idea either...

**Comment by TuckerAndrews3** [comment]
My bad.. I didn't know what it would do to be honest, I've worked with your plugin for about 7 years now and I had just figured it would probably help.. the .db is attached, I will reupload the world, it's good to know that they work now because we really liked these planets. The question is, though, why was this error happening if the plugin now supports it?

https://www.dropbox.com/s/15fi4wom7n92im4/TARDIS.db?dl=0

**Comment by eccentricdevotion** [comment]
Should be fixed in build 2194

**Comment by TuckerAndrews3** [comment]
@eccentricdevotion So no needed changes to the TARDIS database?

**Comment by eccentricdevotion** [comment]
No, any incorrect entries will be dealt with on the fly
