### ISSUE TITLE
TARDIS archives from older MC versions no longer working on 1.16

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#366]
**Describe the bug**
When players try to grow an archive they saved in an older version (1.15 probably but people experiencing it can't remember for sure), the grow fails and console starts getting spammed repeatedly with the error attached below. It doesn't stop spamming until I /tardis abort the task number.

The last line implies it's because the blocks are saved as block data, which has changed for some blocks (walls) in 1.16 (the east/west etc tags are now `low/tall/none` instead of `true/false`), and so it's failing.

I can try and upload a TARDIS.db if necessary but hopefully there's enough info here.

**Log files**
```
WARN Task #25889504 for TARDIS v4.5.3-b2199 generated an exception
INFO java.lang.IllegalArgumentException: Could not parse data: minecraft:cobblestone_wall[east=false,north=false,south=false,up=true,waterlogged=false,west=false]
INFO at org.bukkit.craftbukkit.v1_16_R2.block.data.CraftBlockData.createNewData(CraftBlockData.java:575) ~[patched_1.16.3.jar:git-Paper-204]
INFO at org.bukkit.craftbukkit.v1_16_R2.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:550) ~[patched_1.16.3.jar:git-Paper-204]
INFO at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_252]
INFO at org.bukkit.craftbukkit.v1_16_R2.block.data.CraftBlockData.newData(CraftBlockData.java:550) ~[patched_1.16.3.jar:git-Paper-204]
INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createBlockData(CraftServer.java:2121) ~[patched_1.16.3.jar:git-Paper-204]
INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createBlockData(CraftServer.java:2114) ~[patched_1.16.3.jar:git-Paper-204]
INFO at me.eccentric_nz.TARDIS.desktop.TARDISFullThemeRunnable.run(TARDISFullThemeRunnable.java:426) ~[?:?]
INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-204]
INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]
INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
INFO Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cobblestone_wall does not accept 'false' for east property at position 32: ...wall[east=<--[HERE]
```

**`/tardis version` output**
```
Server version: git-Paper-204 (MC: 1.16.3)
TARDIS version: 4.5.3-b2199
TARDISChunkGenerator version: 4.5.3
Multiverse-Core version: 4.1.1-SNAPSHOT-b777
WorldBorder version: 1.9.10 (beta)
WorldGuard version: 7.0.4-SNAPSHOT+2071-0e73b50
```
A few versions out of date but I didn't see any recent changes that would fix this.

Thanks!

**Comment by eccentricdevotion** [comment]
Minecraft has changed the BlockData values for walls, so any old archive containing a wall of any sort will now fail.
I guess I'll have to code a converter...

**Comment by eccentricdevotion** [comment]
TARDIS.db file would be good for testing database updating/conversion

**Comment by DrPepplies** [comment]
> TARDIS.db file would be good for testing database updating/conversion

Hopefully this works https://we.tl/t-DpXICc30Qu

I'm not sure who's archive it is
