### ISSUE TITLE
Spam NullPointerException from trying to grow new desktop

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#367]
**Describe the bug**
Console starts getting spammed massively when players try to /tardis desktop. Not sure what caused it specifically or which console they chose, but it doesn't grow after they do it.

Doesn't stop until I `/tardis abort` the number.

**Log files**
```
WARN Task #2560894 for TARDIS v4.5.3-b2199 generated an exception
INFO java.lang.NullPointerException: null
INFO at me.eccentric_nz.TARDIS.desktop.TARDISFullThemeRunnable.run(TARDISFullThemeRunnable.java:204) ~[?:?]
INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-204]
INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-204]
INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]
INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**`/tardis version` output**
```
Server version: git-Paper-204 (MC: 1.16.3)
TARDIS version: 4.5.3-b2199
TARDISChunkGenerator version: 4.5.3
Multiverse-Core version: 4.1.1-SNAPSHOT-b777
WorldBorder version: 1.9.10 (beta)
WorldGuard version: 7.0.4-SNAPSHOT+2071-0e73b50
```

Thanks!

**Comment by eccentricdevotion** [comment]
Time Rotor item frame record has not been updated, probably due to previous errors
