### ISSUE TITLE
If player starts growing a TARDIS seed when there is already another one growing, the interior is shared by both TARDIS.

### ISSUE THREAD

**Issue by vistaero** [eccentricdevotion/TARDIS#384]
1. Player 1 places factory seed and right-click it with the key.
2. Player 2 places coral seed and right-click it with the key a few seconds later.
3. Player 1 TARDIS interior stops growing and player 2 TARDIS interior starts growing in the same place.
4. Player 1 TARDIS exterior leads to player 2 TARDIS.

![2020-12-27_01 27 20](https://user-images.githubusercontent.com/4535360/103161511-35c23380-47e3-11eb-9e8b-f8f7002bc482.png)

![2020-12-27_01 27 13](https://user-images.githubusercontent.com/4535360/103161514-38248d80-47e3-11eb-98b5-848533652f6c.png)

After deleting both TARDIS, I got this errors:

`[01:16:20 INFO]: vistaero issued server command: /tardisadmin delete vistaero
[01:16:22 WARN]: Task #33615 for TARDIS v4.5.4-b18.12.20-00:54 generated an exception
java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.remove(CraftPlayer.java:2056) ~[patched_1.16.4.jar:git-Paper-331]
	at me.eccentric_nz.TARDIS.builders.TARDISInteriorPostioning.reclaimChunks(TARDISInteriorPostioning.java:210) ~[?:?]
	at me.eccentric_nz.TARDIS.destroyers.TARDISDestroyerInner.destroyInner(TARDISDestroyerInner.java:71) ~[?:?]
	at me.eccentric_nz.TARDIS.commands.admin.TARDISDeleteCommand.lambda$deleteTARDIS$2(TARDISDeleteCommand.java:184) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-331]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-331]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[01:16:34 INFO]: vistaero issued server command: /tardisadmin delete Lariza
[01:16:36 WARN]: Task #33810 for TARDIS v4.5.4-b18.12.20-00:54 generated an exception
java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.remove(CraftPlayer.java:2056) ~[patched_1.16.4.jar:git-Paper-331]
	at me.eccentric_nz.TARDIS.builders.TARDISInteriorPostioning.reclaimChunks(TARDISInteriorPostioning.java:195) ~[?:?]
	at me.eccentric_nz.TARDIS.destroyers.TARDISDestroyerInner.destroyInner(TARDISDestroyerInner.java:71) ~[?:?]
	at me.eccentric_nz.TARDIS.commands.admin.TARDISDeleteCommand.lambda$deleteTARDIS$2(TARDISDeleteCommand.java:184) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-331]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-331]
	at java.lang.Thread.run(Thread.java:832) [?:?]`

```
[01:32:45 INFO]: §6[TARDIS]§r Server version: §bgit-Paper-331 (MC: 1.16.4)
[01:32:45 INFO]: §6[TARDIS]§r TARDIS version: §b4.5.4-b18.12.20-00:54
[01:32:45 INFO]: §6[TARDIS]§r TARDISChunkGenerator version: §b4.5.4
[01:32:45 INFO]: §6[TARDIS]§r WorldGuard version: §b7.0.4+f7ff984
[01:32:45 INFO]: §6[TARDIS]§r Multiverse-Core version: §b4.1.0-b775
```

**Comment by PrincessRTFM** [comment]
That's actually kinda awesome, if you can make it a feature. Two TARDISes, intertwined, exteriors split by time and space but interiors joint as one...

Especially if you can make them _both_ count as Timelords instead of one being a companion, that'd be pretty cool!

**Comment by eccentricdevotion** [comment]
#194

**Comment by eccentricdevotion** [comment]
Error has nothing to do with shared interiors - a player was in the TARDIS when it was being deleted (according to the log)

**Comment by Technoguyfication** [comment]
I was able to reproduce this while working on the `/tadmin delete` command improvements. I had two accounts place a seed block and both click their seed block with a key right after another. Easiest way to fix it would probably be to just allocate TIPS slots atomically on the same tick that the block is clicked.

**Comment by Technoguyfication** [comment]
Can confirm this is fixed in the latest build
