### ISSUE TITLE
TARDIS Areas: Default direction?

### ISSUE THREAD

**Issue by 19lmyers** [eccentricdevotion/TARDIS#387]
I would like a mechanism, perhaps a subcommand of `/tardisarea`, that lets you set the default direction for a given area.
This way, TARDISes that travel to the area would materialize facing the given direction instead of north.

**Comment by eccentricdevotion** [comment]
`/tardisarea [area] direction [NORTH|EAST|SOUTH|WEST|NONE]`

**Comment by 19lmyers** [comment]
I'm getting this console error when I run the command:
```
[TARDIS]: Plugin TARDIS v4.5.5-b2216 generated an exception while executing task 113952
java.lang.StringIndexOutOfBoundsException: start 0, end -5, length 0
at java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1724) ~[?:?]
at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:1017) ~[?:?]
at java.lang.StringBuilder.substring(StringBuilder.java:85) ~[?:?]
at me.eccentric_nz.TARDIS.database.TARDISSQLUpdate.run(TARDISSQLUpdate.java:76) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-339]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-339]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-339]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

Noticed this when I realized the direction setting wasn't working...

**Comment by eccentricdevotion** [comment]
Fixed 0e9b9b2 build 2217

**Comment by 19lmyers** [comment]
Updated to build 2217... Using an area disk on my server after running the command still results in the TARDIS facing SOUTH, regardless of the value passed to the command. 
I used a SQLite browser to check the database, and it correctly matches my selected value, however.

**Comment by eccentricdevotion** [comment]
TARDIS area disks don't currently hold directional information... does it work if you use the `/tardistravel area [area]` command?

**Comment by 19lmyers** [comment]
It does, which is a bit odd if you ask me. I would think using the area disk should result in the same behavior as the area travel command...

**Comment by eccentricdevotion** [comment]
It will in the next build...

**Comment by roberestarkk** [comment]
Would be wonderful if you could get it to work for /tremote travel as well, as I use that to retrieve all the inactive TARDIS' and park them and my OCD wants them to face the same way lol

**Comment by eccentricdevotion** [comment]
> Would be wonderful if you could get it to work for /tremote travel as well

Build 2391

**Comment by eccentricdevotion** [comment]
@roberestarkk 
2bdb28a

**Comment by roberestarkk** [comment]
Thank you! :)
