### ISSUE TITLE
Custom dimensions (Skaro, Gallifrey, Siluria) crash the server

### ISSUE THREAD

**Issue by eccentricdevotion** [eccentricdevotion/TARDIS#484]
**Describe the bug**
The custom TARDIS dimensions loaded via datapacks cause the server to crash, as Spigot has added support for them, but fails to load them.
This seems to also happen with non-TARDIS datapacks, but more testing is needed.

Spigot 3043 / Paper 594 and higher...

**Log files**

```
[16:00:24] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Unregistered dimension type: net.minecraft.server.v1_16_R3.DimensionManager@6a1c10ce
	at net.minecraft.server.v1_16_R3.World.lambda$new$0(World.java:196) ~[patched_1.16.5.jar:git-Paper-594]
	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
	at net.minecraft.server.v1_16_R3.World.<init>(World.java:195) ~[patched_1.16.5.jar:git-Paper-594]
	at net.minecraft.server.v1_16_R3.WorldServer.<init>(WorldServer.java:324) ~[patched_1.16.5.jar:git-Paper-594]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:557) ~[patched_1.16.5.jar:git-Paper-594]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-594]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-594]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-594]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by eccentricdevotion** [comment]
Update to TARDIS & TARDISChunkGenerator 4.6.0 before updating to Spigot 3043 / Paper 594 and higher...

**Comment by eccentricdevotion** [comment]
Temporary solution as server now has duplicate dimensions - still needs a bit more thought

**Comment by eccentricdevotion** [comment]
Found I had to delete the spawn chunks after travelling to some other part of the world to get the dimension to load properly (eg custom sky and water colours) and also to prevent immense lag when teleport to the world's spawn point.

I just removed the relevant region files from the world folders eg deleting these files seemed to work:

- r.-1.-1.mca,
- r.0.0.mca,
- r.-1.0.mca,
- r.0.-1.mca
