### ISSUE TITLE
TARDIS construct command broken

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#502]
**Describe the bug**
`/tardis construct` causes internal errors.

**To Reproduce**
1. Run `/tardis construct`

**Log files**
Paste your server log (_showing the whole server startup to when the error occurs_) on a website like pastebin.com, and post a link here. Even if there are no errors in the log, it still contains useful information for troubleshooting.
```
12.05 23:49:11 [Server] INFO DalekCraft issued server command: /tardis construct
12.05 23:49:11 [Server] ERROR null
12.05 23:49:11 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tardis' in plugin TARDIS v4.6.1-b2263
12.05 23:49:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
12.05 23:49:11 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
12.05 23:49:11 [Server] INFO at me.eccentric_nz.TARDIS.commands.tardis.TARDISConstructCommand.setLine(TARDISConstructCommand.java:56) ~[?:?]
12.05 23:49:11 [Server] INFO at me.eccentric_nz.TARDIS.commands.tardis.TARDISCommands.onCommand(TARDISCommands.java:123) ~[?:?]
12.05 23:49:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
12.05 23:49:11 [Server] INFO ... 19 more
```

**`/tardis version` output**
Please include an output of your `/tardis version`.
```
17:50:42.356
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Server version: git-Paper-"809466f2e" (MC: 1.16.5)
17:50:42.356
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] TARDIS version: 4.6.1-b2263
17:50:42.356
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] TARDISChunkGenerator version: 4.6.1
17:50:42.356
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] PlaceholderAPI version: 2.10.9
17:50:42.361
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] LibsDisguises version: 10.0.24
17:50:42.361
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Essentials version: 2.18.2.0
17:50:42.361
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] WorldGuard version: 7.0.4+f7ff984
17:50:42.361
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Multiverse-Core version: 4.2.2-b812
17:50:42.361
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] WorldBorder version: 2.1.1
17:50:42.361
[17:50:42] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Checking for new TARDIS builds...
```

**Comment by eccentricdevotion** [comment]
Duplicates #495
