### ISSUE TITLE
/trecipe Accessories category does not open

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#505]
**Describe the bug**
The Accessories category in `/trecipe` simply does not open.

Edit: Also happens with the Food category.

**To Reproduce**
1. Run `/trecipe`
2. Attempt to open the Accessories or Food categories

**Log files**
Paste your server log (_showing the whole server startup to when the error occurs_) on a website like pastebin.com, and post a link here. Even if there are no errors in the log, it still contains useful information for troubleshooting.
```
16.05 15:44:35 [Server] INFO DalekCraft issued server command: /trecipe
16.05 15:44:36 [Server] WARN [TARDIS] Task #6040 for TARDIS v4.6.1-b2265 generated an exception
16.05 15:44:36 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ShapedRecipe.getResult()" because "shaped" is null
16.05 15:44:36 [Server] INFO at me.eccentric_nz.TARDIS.recipes.TARDISRecipeInventory.getItemStack(TARDISRecipeInventory.java:74) ~[?:?]
16.05 15:44:36 [Server] INFO at me.eccentric_nz.TARDIS.recipes.TARDISRecipeInventory.<init>(TARDISRecipeInventory.java:35) ~[?:?]
16.05 15:44:36 [Server] INFO at me.eccentric_nz.TARDIS.recipes.TARDISRecipeCategoryListener.lambda$onRecipeCategoryClick$0(TARDISRecipeCategoryListener.java:41) ~[?:?]
16.05 15:44:36 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-"809466f2e"]
16.05 15:44:36 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```

**`/tardis version` output**
Please include an output of your `/tardis version`.
```
09:46:45.024
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Server version: git-Paper-"809466f2e" (MC: 1.16.5)
09:46:45.024
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] TARDIS version: 4.6.1-b2265
09:46:45.024
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] TARDISChunkGenerator version: 4.6.1
09:46:45.027
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] PlaceholderAPI version: 2.10.9
09:46:45.027
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] LibsDisguises version: 10.0.24
09:46:45.027
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Essentials version: 2.18.2.0
09:46:45.028
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] WorldGuard version: 7.0.4+f7ff984
09:46:45.028
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Multiverse-Core version: 4.2.2-b812
09:46:45.028
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] CoreProtect version: 19.5
09:46:45.028
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] WorldBorder version: 2.1.1
09:46:45.028
[09:46:45] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [TARDIS] Checking for new TARDIS builds...
```

**Comment by eccentricdevotion** [comment]
Fixed in build 2266
