### ISSUE TITLE
Repetitive Error Message

### ISSUE THREAD

**Issue by CorruptTraveler** [eccentricdevotion/TARDIS#54]
[17:47:16 WARN]: [TARDIS] Task #23 for TARDIS v3.8.3-b1684 generated an exception
java.lang.NullPointerException: null
        at me.eccentric_nz.TARDIS.control.TARDISControlRunnable.run(TARDISControlRunnable.java:79) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

I've already loaded in all the TARDIS worlds using the Multiverse Core and deleted TARDIS' that I didn't want. But this keeps on popping up in my server's console every now and then. Still no idea what it means.

**Comment by eccentricdevotion** [comment]
Most probably still records in the database for a world that no longer exists.
How did you delete TARDISes?

**Comment by eccentricdevotion** [comment]
Might be best to start fresh with the TARDIS plugin - delete the TARDIS folder, remove all TARDIS worlds from Multiverse and the server folder, restart the server.

**Comment by CorruptTraveler** [comment]
I deleted the TARDIS' using the /tardisadmin delete [player] command.

**Comment by eccentricdevotion** [comment]
Try deleting the abandoned TARDISes as well.

**Comment by CorruptTraveler** [comment]
How would I do that?

**Comment by eccentricdevotion** [comment]
Seeing as the world doesn't exist anymore, you'll probably have to edit the database file.
You could the the '/tardisadmin list abandoned' command... https://eccentricdevotion.github.io/TARDIS/abandon.html

**Comment by eccentricdevotion** [comment]
Found the issue in the code. Have made a new build that fixes the error.
http://tardisjenkins.duckdns.org:8080/job/TARDIS/1688/
If you're using the TerrainControl plugin you'll need to update to v2.9.0-SNAPSHOT - you can get it here: https://github.com/eccentricdevotion/TARDIS/blob/v3.7/lib/TerrainControl.jar

**Comment by CorruptTraveler** [comment]
[02:32:57 WARN]: [TARDIS] Task #36 for TARDIS v3.8.3-b1688 generated an exception
java.lang.NullPointerException: null
	at me.eccentric_nz.TARDIS.utility.TARDISHumSounds.lambda$new$419(TARDISHumSounds.java:52) ~[?:?]
	at me.eccentric_nz.TARDIS.utility.TARDISHumSounds$2$1.run(TARDISHumSounds.java:105) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

Something with the TARDIS Hum??

**Comment by PrincessRTFM** [comment]
@eccentricdevotion When there's a problem in the plugin database, which has happened on my private beta server a few times, I just delete the `TARDIS.db` file and any TARDIS worlds, so I keep my configs. If it's a _small_ problem, I open the database in a sqlite browser and look through it, like when I accidentally hid my HADS-dispersed TARDIS and couldn't rebuild it.
