### ISSUE TITLE
java.lang.NullPointerException: Name is null

### ISSUE THREAD

**Issue by Rocologo** [eccentricdevotion/TARDIS#548]
**Describe the bug**
I get this error in the console when ever Tardis is enabled. Im running on a SpigotMC 1.17.1 server.

```
[11:19:50] [Server thread/ERROR]: Error occurred while enabling TARDIS v4.7.5-b2344 (Is it up to date?)
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:271) ~[?:?]
	at org.bukkit.Material.valueOf(Material.java:1) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at me.eccentric_nz.TARDIS.recipes.TARDISShapelessRecipe.makeRecipe(TARDISShapelessRecipe.java:60) ~[?:?]
	at me.eccentric_nz.TARDIS.recipes.TARDISShapelessRecipe.lambda$addShapelessRecipes$0(TARDISShapelessRecipe.java:48) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.eccentric_nz.TARDIS.recipes.TARDISShapelessRecipe.addShapelessRecipes(TARDISShapelessRecipe.java:48) ~[?:?]
	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:414) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
**`/tardis version` output**
Please include an output of your `/tardis version`.

**Comment by eccentricdevotion** [comment]
Delete recipes.yml and try again

**Comment by Rocologo** [comment]
it worked
