### ISSUE TITLE
TARDIS throwing error and not loading whilst updating to Tuinity (paper) 1.17.1

### ISSUE THREAD

**Issue by TuckerAndrews3** [eccentricdevotion/TARDIS#555]
The plugin is throwing this error upon starting up with 1.17.1, I am using Build #2346 on the Jenkins and Tuinity git-Tuinity-23 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ce43ccd on HEAD)

The plugin seems to be having issues starting and it's talking about a.. grass path?

> [18:30:15] [Server thread/INFO]: [TARDIS] Enabling TARDIS v4.7.5-b2346
[18:30:15] [Server thread/INFO]: [TARDIS] Loading language: ENGLISH
[18:30:15] [Server thread/ERROR]: Error occurred while enabling TARDIS v4.7.5-b2346 (Is it up to date?)
java.lang.IllegalArgumentException: Could not parse data: minecraft:grass_path
	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525) ~[patched_1.17.1.jar:git-Tuinity-23]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2241) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2234) ~[patched_1.17.1.jar:git-Tuinity-23]
	at me.eccentric_nz.TARDIS.database.resultset.ResultSetBlocks.resultSet(ResultSetBlocks.java:103) ~[?:?]
	at me.eccentric_nz.TARDIS.files.TARDISBlockLoader.loadProtectedBlocks(TARDISBlockLoader.java:56) ~[?:?]
	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:442) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Tuinity-23]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Tuinity-23]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710) ~[patched_1.17.1.jar:git-Tuinity-23]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:307) ~[patched_1.17.1.jar:git-Tuinity-23]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Tuinity-23]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Tuinity-23]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:grass_path' at position 0: <--[HERE]
[18:30:15] [Server thread/INFO]: [TARDIS] Disabling TARDIS v4.7.5-b2346

**Comment by TuckerAndrews3** [comment]
Just wanted to comment that I'm also using TARDISChunkGenerator #135

**Comment by eccentricdevotion** [comment]
They changed grass paths to dirt paths in 1.17… looks like there are some database entries using the old block data. I’ll work on a fix tonight.

**Comment by TuckerAndrews3** [comment]
Thank you!

**Comment by TuckerAndrews3** [comment]
Please reply here when you update the plugin so I can make sure I see it

**Comment by eccentricdevotion** [comment]
Building now on Jenkins

**Comment by TuckerAndrews3** [comment]
Thank you! Now works
