### ISSUE TITLE
Missing argument in Enum for Admin Config GUI

### ISSUE THREAD

**Issue by runesage** [eccentricdevotion/TARDIS#570]
**Describe the bug**
Trying to open Admin Config GUI throws exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on "Admin Config Menu" in the GUI

**Screenshots**
N/A

**Log files**
[13:50:16] [Server thread/WARN]: [TARDIS] Task #65105 for TARDIS v4.7.6-b2356 generated an exception
java.lang.IllegalArgumentException: No enum constant me.eccentric_nz.TARDIS.custommodeldata.GUIConfiguration.SWITCH_RESOURCE_PACKS
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at me.eccentric_nz.TARDIS.custommodeldata.GUIConfiguration.valueOf(GUIConfiguration.java:22) ~[?:?]
        at me.eccentric_nz.TARDIS.commands.config.TARDISConfigMenuInventory.lambda$getItemStack$0(TARDISConfigMenuInventory.java:57) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.eccentric_nz.TARDIS.commands.config.TARDISConfigMenuInventory.getItemStack(TARDISConfigMenuInventory.java:51) ~[?:?]
        at me.eccentric_nz.TARDIS.commands.config.TARDISConfigMenuInventory.<init>(TARDISConfigMenuInventory.java:39) ~[?:?]
        at me.eccentric_nz.TARDIS.commands.preferences.TARDISPrefsMenuListener.lambda$onPrefsMenuClick$3(TARDISPrefsMenuListener.java:254) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**`/tardis version` output**
>tardis version
[13:51:01] [Server thread/INFO]: [TARDIS] Server version: 3284-Spigot-3892929-0ebef35 (MC: 1.17.1)
[13:51:01] [Server thread/INFO]: [TARDIS] TARDIS version: 4.7.6-b2356
[13:51:01] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.7.6
[13:51:01] [Server thread/INFO]: [TARDIS] dynmap version: 3.2-beta-3-514
[13:51:01] [Server thread/INFO]: [TARDIS] Essentials version: 2.19.0
[13:51:01] [Server thread/INFO]: [TARDIS] WorldBorder version: 1.9.10 (beta)
[13:51:01] [Server thread/INFO]: [TARDIS] Multiverse-Core version: 4.3.1-b861
[13:51:01] [Server thread/INFO]: [TARDIS] Multiverse-Inventories version: 4.2.1-b490
[13:51:01] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.6+1cff55f
[13:51:01] [Server thread/INFO]: [TARDIS] Towny version: 0.96.3.0
[13:51:01] [Server thread/INFO]: [TARDIS] Checking for new TARDIS builds...

**Comment by eccentricdevotion** [comment]
**Could you attach your _plugins/TARDIS/config.yml_ (before editing!) to this issue please**

The `switch_resource_packs` config option should be in _planets.yml_, and not in the config so:

- Open _plugins/TARDIS/config.yml_
- Find the `switch_resource_packs` config option
- Delete that whole line
- Save the file
- Restart the server

I'll add a check for old config options and remove them if they're present (which I usually do, but I must have missed that one...) having you unedited config file will help :)

**Comment by runesage** [comment]
That makes a lot of sense! I just did a version 1.16.5 to 1.17.1 upgrade of my server. Much appreciated for all the work you do with this mod. I have been an avid user of it for years. Attached below is a copy of my config. This server has been around since 1.14 so I have been through a few upgrades.

[config.yml.txt](https://github.com/eccentricdevotion/TARDIS/files/7612681/config.yml.txt)
