### ISSUE TITLE
HADS Dispersal Error

### ISSUE THREAD

**Issue by runesage** [eccentricdevotion/TARDIS#571]
**Describe the bug**
Plugin throws and error exception when Dispersal HADS mode is active. HADS Dispersal doesn't work. HADs Displacement mode works correctly however.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable HADS
2. Set HADS to Dispersal
3. Attack TARDIS to initiate HADS

**Screenshots**
N/A

**Log files**
[14:39:59] [Server thread/ERROR]: Could not pass event BlockDamageEvent to TARDIS v4.7.6-b2356
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:574) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:238) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1466) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WALL_SOUL_TORCH
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:1) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]
        at me.eccentric_nz.TARDIS.hads.TARDISHostileDispersal.lambda$buildList$3(TARDISHostileDispersal.java:205) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.eccentric_nz.TARDIS.hads.TARDISHostileDispersal.buildList(TARDISHostileDispersal.java:205) ~[?:?]
        at me.eccentric_nz.TARDIS.hads.TARDISHostileDispersal.<init>(TARDISHostileDispersal.java:59) ~[?:?]
        at me.eccentric_nz.TARDIS.hads.TARDISHostileAction.processAction(TARDISHostileAction.java:62) ~[?:?]
        at me.eccentric_nz.TARDIS.listeners.TARDISBlockDamageListener.onPoliceBoxDamage(TARDISBlockDamageListener.java:96) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor477.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-latest.jar:3284-Spigot-3892929-0ebef35]

**`/tardis version` output**
[14:42:42] [Server thread/INFO]: [TARDIS] Server version: 3284-Spigot-3892929-0ebef35 (MC: 1.17.1)
[14:42:42] [Server thread/INFO]: [TARDIS] TARDIS version: 4.7.6-b2356
[14:42:42] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.7.6
[14:42:42] [Server thread/INFO]: [TARDIS] dynmap version: 3.2-beta-3-514
[14:42:42] [Server thread/INFO]: [TARDIS] Essentials version: 2.19.0
[14:42:42] [Server thread/INFO]: [TARDIS] WorldBorder version: 1.9.10 (beta)
[14:42:42] [Server thread/INFO]: [TARDIS] Multiverse-Core version: 4.3.1-b861
[14:42:42] [Server thread/INFO]: [TARDIS] Multiverse-Inventories version: 4.2.1-b490
[14:42:42] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.6+1cff55f
[14:42:42] [Server thread/INFO]: [TARDIS] Towny version: 0.96.3.0
[14:42:42] [Server thread/INFO]: [TARDIS] Checking for new TARDIS builds...

**Comment by eccentricdevotion** [comment]
- Open _plugins/TARDIS/blocks.yml_
- Find the `under_door_blocks` section
- Find `- WALL_SOUL_TORCH`
- Change to `- SOUL_WALL_TORCH`
- Save file
- Restart server

Will be fixed in next build (for 1.18-rc3)

**Comment by runesage** [comment]
That worked, thanks
