### ISSUE TITLE
Tardis Recipie command bug

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#608]
### Describe the bug

When using the command /tardisrecipe and then clicking on the accessories tab the error below appears

```
[18:08:53 WARN]: [TARDIS] Task #456 for TARDIS v4.8.3-b2406 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ShapedRecipe.getResult()" because "shaped" is null
        at me.eccentric_nz.TARDIS.recipes.TARDISRecipeInventory.getItemStack(TARDISRecipeInventory.java:90) ~[TARDIS.jar:?]
        at me.eccentric_nz.TARDIS.recipes.TARDISRecipeInventory.<init>(TARDISRecipeInventory.java:51) ~[TARDIS.jar:?]
        at me.eccentric_nz.TARDIS.recipes.TARDISRecipeCategoryListener.lambda$onRecipeCategoryClick$0(TARDISRecipeCategoryListener.java:57) ~[TARDIS.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

1) Paper
2) Tardis
3) /tardisrecipe
4) Click accessories
5) error

### Log files

https://paste.gg/p/anonymous/085f69ca895d4ccda460ef30ee552022

### '/tardis version' output

[18:11:33 INFO]: [TARDIS] Server version: git-Paper-197 (MC: 1.18.1)
[18:11:33 INFO]: [TARDIS] TARDIS version: 4.8.3-b2406
[18:11:33 INFO]: [TARDIS] TARDISChunkGenerator version: 4.8.3
[18:11:33 INFO]: [TARDIS] PlaceholderAPI version: 2.11.2-DEV-148
[18:11:33 INFO]: [TARDIS] LibsDisguises version: 10.0.27
[18:11:33 INFO]: [TARDIS] Essentials version: 2.19.3-dev+15-19837f9
[18:11:33 INFO]: [TARDIS] Multiverse-Core version: 4.3.2-SNAPSHOT-b868
[18:11:33 INFO]: [TARDIS] Checking for new TARDIS builds...
[18:11:34 INFO]: [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
Cannot reproduce:

https://user-images.githubusercontent.com/1841924/155777784-96a620e7-38ac-4073-b078-b4c8fee1374b.mp4

Try deleting _plugins/TARDIS/recipes.yml_  and let it regenerate

**Comment by eccentricdevotion** [comment]
Could you attach your _recipes.yml_ file here before you remove it please.

**Comment by eccentricdevotion** [comment]
You have 532 other (non-TARDIS) recipe related errors...

**Comment by LozoTrioxide** [comment]
Yeah im aware of those, different plugin.

Heres the file 
https://paste.gg/p/anonymous/4adfcc3d846b45b39e1edc58fb648809

**Comment by LozoTrioxide** [comment]
Looks like deleting it didnt help, ive fixed the other 500 recipies though lol

**Comment by eccentricdevotion** [comment]
Fixed.
Problem was it was trying to load the recipe for the Vortex Manipulator, but you don't have that plugin installed...
