### ISSUE TITLE
Tardis Plugin 1.16.5 does not load

### ISSUE THREAD

**Issue by LegendarySpork9** [eccentricdevotion/TARDIS#648]
### Describe the bug

Hello,

I hope you are well.

I have been trying to setup a craftbucket 1.16.5 server lately and I am running java 11 as the server will not work with java 16. The issue I am having is that the Tardis.jar will not enable due to the following error:

_me/eccentric_nz/TARDIS/TARDIS has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0_

60.0 is Java 16. I don't really want to upgrade to 1.17 so I am hoping there is something that you can do to help surrounding this  issue. The chunk loader enables fine but the tardis.jar will not.

I look forward to hearing from you.

Cheers,

LS9

### To Reproduce

1. Install craftbucket server 1.16.5
2. setup the server as normal
3. add the tardis files into the plugins folder
4. run the server

### Screenshots

![image](https://user-images.githubusercontent.com/100041525/173136081-6039e060-1814-4571-bf63-f1c45b3f96c2.png)
![image](https://user-images.githubusercontent.com/100041525/173136096-76f92285-8317-400c-a6f1-2a3efba5c36c.png)
![image](https://user-images.githubusercontent.com/100041525/173136564-9e6f7e2a-56b8-434d-a693-bffe72745c0d.png)

### Log files

```
Paste configs or paste.gg link here!
```
*** Error, this build is outdated ***
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
*** Server will start in 20 seconds ***
Loading libraries, please wait...
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[19:29:24] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:29:25] [main/INFO]: Reloading ResourceManager: Default, bukkit
[19:29:26] [Worker-Main-13/INFO]: Loaded 7 recipes
[19:29:24] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:29:25] [main/INFO]: Reloading ResourceManager: Default, bukkit
[19:29:26] [Worker-Main-13/INFO]: Loaded 7 recipes
[19:29:27] [Server thread/INFO]: Starting minecraft server version 1.16.5
[19:29:27] [Server thread/INFO]: Loading properties
[19:29:27] [Server thread/INFO]: Default game type: SURVIVAL
[19:29:27] [Server thread/INFO]: Generating keypair
[19:29:27] [Server thread/INFO]: Starting Minecraft server on 46.251.234.112:34400
[19:29:28] [Server thread/INFO]: Using epoll channel type
[19:29:28] [Server thread/INFO]: This server is running CraftBukkit version 2991-Bukkit-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[19:29:29] [Server thread/ERROR]: Could not load 'plugins/TARDIS.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/eccentric_nz/TARDIS/TARDIS has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:179) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:787) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: me/eccentric_nz/TARDIS/TARDIS has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
	... 7 more
[19:29:29] [Server thread/INFO]: [TARDISChunkGenerator] Loading TARDISChunkGenerator v4.6.4
[19:29:29] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v4.2.2-b812
[19:29:29] [Server thread/INFO]: [Multiverse-SignPortals] Loading Multiverse-SignPortals v4.2.0-b762
[19:29:29] [Server thread/INFO]: [Multiverse-Inventories] Loading Multiverse-Inventories v4.2.1-b490
[19:29:29] [Server thread/INFO]: [TARDISChunkGenerator] Enabling TARDISChunkGenerator v4.6.4
[19:29:29] [Server thread/INFO]: Preparing level "Pre 1_17"
[19:29:29] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:29:31] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:31] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:31] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:31] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:31] [Server thread/INFO]: Preparing spawn area: 84%
[19:29:31] [Server thread/INFO]: Time elapsed: 2144 ms
[19:29:31] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[19:29:32] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:32] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:32] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:33] [Server thread/INFO]: Preparing spawn area: 21%
[19:29:33] [Server thread/INFO]: Preparing spawn area: 83%
[19:29:34] [Worker-Main-12/INFO]: Preparing spawn area: 86%
[19:29:34] [Worker-Main-8/INFO]: Preparing spawn area: 87%
[19:29:35] [Worker-Main-12/INFO]: Preparing spawn area: 87%
[19:29:35] [Worker-Main-8/INFO]: Preparing spawn area: 87%
[19:29:36] [Worker-Main-8/INFO]: Preparing spawn area: 88%
[19:29:36] [Worker-Main-12/INFO]: Preparing spawn area: 90%
[19:29:37] [Worker-Main-14/INFO]: Preparing spawn area: 93%
[19:29:37] [Worker-Main-13/INFO]: Preparing spawn area: 97%
[19:29:38] [Server thread/INFO]: Time elapsed: 6273 ms
[19:29:38] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[19:29:38] [Server thread/INFO]: Preparing spawn area: 0%
[19:29:38] [Server thread/INFO]: Preparing spawn area: 83%
[19:29:39] [Worker-Main-10/INFO]: Preparing spawn area: 97%
[19:29:39] [Server thread/INFO]: Time elapsed: 1061 ms
[19:29:39] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.2-b812
[19:29:39] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[19:29:39] [Server thread/INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[19:29:39] [Server thread/WARN]: [Multiverse-Core] Invalid world name 'Pre 1_17'
[19:29:39] [Server thread/WARN]: [Multiverse-Core] World name should not contain spaces or special characters!
[19:29:39] [Server thread/WARN]: [Multiverse-Core] Invalid world name 'Pre 1_17_nether'
[19:29:39] [Server thread/WARN]: [Multiverse-Core] World name should not contain spaces or special characters!
[19:29:39] [Server thread/WARN]: [Multiverse-Core] Invalid world name 'Pre 1_17_the_end'
[19:29:39] [Server thread/WARN]: [Multiverse-Core] World name should not contain spaces or special characters!
[19:29:39] [Server thread/INFO]: [Multiverse-Core] 0 - World(s) loaded.
[19:29:39] [Server thread/WARN]: [Multiverse-Core] The world specified as the spawn world (null) did not exist!!
[19:29:39] [Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[19:29:39] [Server thread/INFO]: [Multiverse-Core] Version 4.2.2-b812 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[19:29:39] [Server thread/INFO]: [Multiverse-SignPortals] Enabling Multiverse-SignPortals v4.2.0-b762
[19:29:39] [Server thread/INFO]: [Multiverse-SignPortals 4.2.0-b762]  Enabled - By Rigby and fernferret
[19:29:39] [Server thread/INFO]: [Multiverse-Inventories] Enabling Multiverse-Inventories v4.2.1-b490
[19:29:40] [Server thread/INFO]: [Multiverse-Inventories 4.2.1-b490] enabled.
[19:29:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:29:40] [Server thread/INFO]: Done (10.891s)! For help, type "help"

### '/tardis version' output

As the plugin wont load, all I can tell you is that it is 1.16.5 from this link:

https://github.com/eccentricdevotion/TARDIS/releases/download/1.16.5/TARDIS_1.16.5.zip

I apologise that I can't be more specific.

**Comment by Chew** [comment]
You need to run Java 16

**Comment by LegendarySpork9** [comment]
Hello Olivia,

I hope you are well.

I understand that that is the case, however CraftBucket 1.16.5 only accepts up to Java 15. Same with Sprigot

Is there anyway around this or is Java 16 the only way?

Thanks in advance,

LS9

**Comment by Chew** [comment]
Paper should load fine: https://api.papermc.io/v2/projects/paper/versions/1.16.5/builds/794/downloads/paper-1.16.5-794.jar

**Comment by eccentricdevotion** [comment]
Paper 1.16.5 does indeed load with Java 16 and enables the TARDIS plugin without issues.

**Comment by LegendarySpork9** [comment]
Hello Both,

I hope you are well.

Thank you for your help, I will use this version as opposed to CraftBucket and close if it works :)

Thanks,

LS9

**Comment by LegendarySpork9** [comment]
Hello Both,

I hope you are well.

That has worked. Thank you very much for your speedy help.

I hope you enjoy your evening or day. (Not sure what time zone you are in)

LS9
