### ISSUE TITLE
Stopped working for some reason.

### ISSUE THREAD

**Issue by roracle** [eccentricdevotion/TARDIS#650]
### Describe the bug

Was working before but no longer.  Just updated a few things, still on 1.18.2
Paper 1.18.2 #386
TARDIS build #2453
TARDISChunkGenerator build #169
TARDISVortexManipulator build #59

Not sure what the issue is.

### To Reproduce

Got the latest server version, updated Essentials and other plugins.

### Log files

Not a full log, but enough to show what's happening:

`[13:19:16] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:19:18] [Worker-Main-1/INFO]: Loaded 7 recipes
[13:19:19] [Server thread/INFO]: Starting minecraft server version 1.18.2
[13:19:19] [Server thread/INFO]: Loading properties
[13:19:19] [Server thread/INFO]: This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
[13:19:19] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:19:19] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:19:19] [Server thread/INFO]: Default game type: SURVIVAL
[13:19:19] [Server thread/INFO]: Generating keypair
[13:19:19] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:19:19] [Server thread/INFO]: Using epoll channel type
[13:19:19] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[13:19:19] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[13:19:20] [Server thread/ERROR]: Could not load 'plugins/TARDISChunkGenerator.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
	at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.18.2.jar:git-Paper-379]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loading 12 libraries... please wait
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/inject/guice/5.0.1/guice-5.0.1.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/javax/inject/javax.inject/1/javax.inject-1.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/guava/guava/30.1-jre/guava-30.1-jre.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/google/inject/extensions/guice-assistedinject/5.0.1/guice-assistedinject-5.0.1.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/io/github/classgraph/classgraph/4.8.114/classgraph-4.8.114.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.5/jackson-dataformat-yaml-2.12.5.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/fasterxml/jackson/core/jackson-databind/2.12.5/jackson-databind-2.12.5.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/fasterxml/jackson/core/jackson-annotations/2.12.5/jackson-annotations-2.12.5.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/yaml/snakeyaml/1.27/snakeyaml-1.27.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/fasterxml/jackson/core/jackson-core/2.12.5/jackson-core-2.12.5.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/fasterxml/jackson/module/jackson-module-parameter-names/2.12.5/jackson-module-parameter-names-2.12.5.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/io/leangen/geantyref/geantyref/1.3.11/geantyref-1.3.11.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/apache/commons/commons-text/1.8/commons-text-1.8.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/jdbi/jdbi3-core/3.22.0/jdbi3-core-3.22.0.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/antlr/antlr4-runtime/4.9.2/antlr4-runtime-4.9.2.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/github/ben-manes/caffeine/caffeine/3.0.3/caffeine-3.0.3.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/jdbi/jdbi3-sqlobject/3.22.0/jdbi3-sqlobject-3.22.0.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/com/h2database/h2/1.4.200/h2-1.4.200.jar
[13:19:20] [Server thread/INFO]: [VanillaTweaks] Loaded library /home/jakethley/rorystuff/18/libraries/org/xerial/sqlite-jdbc/3.36.0.3/sqlite-jdbc-3.36.0.3.jar
[13:19:20] [Server thread/ERROR]: Could not load 'plugins/TARDIS.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [TARDISChunkGenerator]. Please download and install these plugins to run 'TARDIS'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:19:20] [Server thread/ERROR]: Could not load 'plugins/TARDISVortexManipulator.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [TARDIS]. Please download and install these plugins to run 'TARDISVortexManipulator'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:19:21] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.25
[13:19:21] [Server thread/INFO]: [TerraformGenerator] Loading TerraformGenerator v8.0.0
[13:19:21] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.1
[13:19:21] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0-b547
[13:19:22] [Server thread/INFO]: [PaperTweaks] Loading VanillaTweaks v0.2.0-SNAPSHOT
[13:19:22] [Server thread/INFO]: [mcMMO] Loading mcMMO v2.1.214
[13:19:22] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[13:19:22] [Server thread/INFO]: [dynmap] Loading dynmap v3.4-beta-3-774
[13:19:22] [Server thread/INFO]: [dynmap] version=git-Paper-379 (MC: 1.18.2)
[13:19:22] [Server thread/INFO]: [dynmap] Mod Support API available
[13:19:22] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.10+1742f98
[13:19:22] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@75cbbc03]
[13:19:22] [Server thread/INFO]: [Essentials] Loading Essentials v2.19.5-dev+19-96c6c95
[13:19:22] [Server thread/INFO]: [EssentialsDiscord] Loading EssentialsDiscord v2.19.5-dev+19-96c6c95
[13:19:22] [Server thread/INFO]: [CommandPanels] Loading CommandPanels v3.17.5.0
[13:19:22] [Server thread/INFO]: [Slimefun] Loading Slimefun vDEV - 1015 (git 2c4f886f)
[13:19:22] [Server thread/INFO]: [HotbarPets] Loading HotbarPets vDEV - 38 (git fa6c871d)
[13:19:22] [Server thread/INFO]: [EcoPower] Loading EcoPower vDEV - 5 (git 5c1ecd68)
[13:19:22] [Server thread/INFO]: [ExoticGarden] Loading ExoticGarden vUNOFFICIAL
[13:19:22] [Server thread/INFO]: [Liquid] Loading Liquid vDEV - 14 (git 0f5346bf)
[13:19:22] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.19.5-dev+19-96c6c95
[13:19:22] [Server thread/INFO]: [ExtraTools] Loading ExtraTools vDEV - 36 (git 922c0324)
[13:19:22] [Server thread/INFO]: [FoxyMachines] Loading FoxyMachines vDEV - 58 (git c2c2b8a7)
[13:19:22] [Server thread/INFO]: [ExtraGear] Loading ExtraGear vDEV - 13 (git c62047e2)
[13:19:22] [Server thread/INFO]: [InfinityExpansion] Loading InfinityExpansion vDEV - 140 (git 0098d2fb)
[13:19:22] [Server thread/INFO]: [ElectricSpawners] Loading ElectricSpawners vDEV - 23 (git 6ec96773)
[13:19:22] [Server thread/INFO]: [SFCalc] Loading SFCalc vDEV - 37 (git dfc0fc41)
[13:19:22] [Server thread/INFO]: [SlimyTreeTaps] Loading SlimyTreeTaps vDEV - 20 (git 963f0383)
[13:19:22] [Server thread/INFO]: [PrivateStorage] Loading PrivateStorage vDEV - 18 (git 5832db21)
[13:19:22] [Server thread/INFO]: [Galactifun] Loading Galactifun vDEV - 63 (git 364ecbf5)
[13:19:22] [Server thread/INFO]: [FluffyMachines] Loading FluffyMachines vDEV - 117 (git d1adabbc)
[13:19:22] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v4.3.2-SNAPSHOT-b867
[13:19:22] [Server thread/INFO]: [DyedBackpacks] Loading DyedBackpacks vDEV - 17 (git 8b329e96)
[13:19:22] [Server thread/INFO]: [Multiverse-Portals] Loading Multiverse-Portals v4.2.2-SNAPSHOT-b850
[13:19:22] [Server thread/INFO]: [Networks] Loading Networks vDEV - 37 (git f1915513)
[13:19:22] [Server thread/INFO]: [CMILib] Loading CMILib v1.2.0.2
[13:19:22] [Server thread/INFO]: [TheNewEconomy] Loading TheNewEconomy v0.1.1.16
[13:19:23] [Server thread/INFO]: [TheNewEconomy] Loading The New Economy with Java Version: 18.0.1
[13:19:23] [Server thread/INFO]: [TheNewEconomy] Hooked into Vault
[13:19:23] [Server thread/INFO]: [Towny] Loading Towny v0.98.2.0
[13:19:23] [Server thread/INFO]: [Jobs] Loading Jobs v5.0.3.0
[13:19:23] [Server thread/INFO]: [LWC] Loading LWC v2.2.7-ad0f824
[13:19:23] [Server thread/INFO]: [QuickShop] Loading QuickShop v5.1.0.8
[13:19:23] [Server thread/INFO]: [QuickShop] QuickShop Reremake - Early boot step - Booting up
[13:19:23] [Server thread/INFO]: [QuickShop] [OK] Signature Verify
[13:19:23] [Server thread/INFO]: [QuickShop] [OK] Plugin Manifest Check
[13:19:23] [Server thread/INFO]: [QuickShop] [OK] Potential Infection Characteristics Check
[13:19:23] [Server thread/INFO]: [QuickShop] Reading the configuration...
[13:19:23] [Server thread/INFO]: [QuickShop] Loading messages translation over-the-air (this may need take a while).
[13:19:23] [Server thread/INFO]: [QuickShop] Translation over-the-air platform selected: Crowdin
[13:19:23] [Server thread/INFO]: [QuickShop] Checking for translation updates, this may need a while...
[13:19:25] [Server thread/INFO]: [QuickShop] Loading up integration modules.
[13:19:25] [Server thread/INFO]: [QuickShop] QuickShop Reremake - Early boot step - Complete
[13:19:25] [Server thread/INFO]: [SlimeTinker] Loading SlimeTinker vDEV - 75 (git bb75aa5a)
[13:19:25] [Server thread/INFO]: [TownyChat] Loading TownyChat v0.96
[13:19:25] [Server thread/INFO]: [Multiverse-NetherPortals] Loading Multiverse-NetherPortals v4.2.3-SNAPSHOT-b808
[13:19:25] [Server thread/INFO]: [Dynmap-Towny] Loading Dynmap-Towny v0.90
[13:19:25] [Server thread/INFO]: [DynamicShop] Loading DynamicShop v3.6.6
[13:19:25] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:19:25] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.25
[13:19:25] [Server thread/INFO]:         __    
[13:19:25] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.25
[13:19:25] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[13:19:25] [Server thread/INFO]: 
[13:19:25] [Server thread/INFO]: [LuckPerms] Loading configuration...
[13:19:25] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[13:19:26] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[13:19:26] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[13:19:26] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1746ms)
[13:19:26] [Server thread/INFO]: [TerraformGenerator] Enabling TerraformGenerator v8.0.0
[13:19:27] [Server thread/INFO]: [TerraformGenerator] Custom Logger Initialized
[13:19:27] [Server thread/INFO]: [TerraformGenerator] bStats Metrics enabled.
[13:19:27] [Server thread/INFO]: [TerraformGenerator] Detected version: v1_18_R2, number: 18.2
[13:19:27] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0-b547
[13:19:27] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[13:19:27] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[13:19:27] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.5-dev+19-96c6c95 which is not a depend or softdepend of this plugin.
[13:19:27] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[13:19:27] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[13:19:27] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[13:19:27] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[13:19:27] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.10+1742f98
[13:19:27] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[13:19:27] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[13:19:27] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R2.PaperweightAdapter as the Bukkit adapter
[13:19:28] [Server thread/INFO]: [LWC] Enabling LWC v2.2.7-ad0f824
[13:19:28] [Server thread/INFO]: [LWC] Connecting to SQLite
[13:19:29] [Server thread/INFO]: Preparing level "world"
[13:19:34] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:19:35] [Server thread/INFO]: Time elapsed: 410 ms
[13:19:35] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[13:19:35] [Server thread/INFO]: Time elapsed: 167 ms
[13:19:35] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[13:19:35] [Server thread/INFO]: Time elapsed: 62 ms
[13:19:35] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.1
[13:19:35] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[13:19:35] [Server thread/INFO]: [PaperTweaks] Enabling VanillaTweaks v0.2.0-SNAPSHOT
[13:19:35] [Server thread/INFO]: [PaperTweaks] Thank you for using PaperTweaks/VanillaTweaks!
[13:19:35] [Server thread/INFO]: [PaperTweaks] If you have any issues, please visit one of the following links for support:
[13:19:35] [Server thread/INFO]: [PaperTweaks]   - https://discord.gg/invite/Np6Pcb78rr
[13:19:35] [Server thread/INFO]: [PaperTweaks]   - https://github.com/MC-Machinations/VanillaTweaks/issues
[13:19:36] [Server thread/INFO]: [VanillaTweaks] You are using the SQLITE database type.
[13:19:38] [Server thread/INFO]: [VanillaTweaks] Loaded 40 modules
[13:19:38] [Server thread/INFO]: [VanillaTweaks] Enabled 6 modules
[13:19:38] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.214
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: config.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: config.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: config.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [Debug] No errors found in config.yml!
[13:19:38] [Server thread/INFO]: [mcMMO] Loading locale from plugins/mcMMO/locales/locale_override.properties
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: advanced.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: advanced.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: advanced.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [Debug] No errors found in advanced.yml!
[13:19:38] [Server thread/INFO]: [mcMMO] Platform String: 1.18.2-R0.1-SNAPSHOT
[13:19:38] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.18.2
[13:19:38] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[13:19:38] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: persistent_data.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: persistent_data.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: persistent_data.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [Debug] No errors found in persistent_data.yml!
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: upgrades_overhaul.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: upgrades_overhaul.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: upgrades_overhaul.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: treasures.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: treasures.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: treasures.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: fishing_treasures.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: fishing_treasures.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: fishing_treasures.yml
[13:19:38] [Server thread/INFO]: [mcMMO] Registering enchantments for Fishing Book...
[13:19:38] [Server thread/INFO]: [mcMMO] Loading mcMMO potions.yml File...
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: coreskills.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: coreskills.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: coreskills.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Initializing config: sounds.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: sounds.yml
[13:19:38] [Server thread/INFO]: [mcMMO] [config] Config initialized: sounds.yml
[13:19:38] [Server thread/INFO]: [mcMMO] Loading mcMMO skillranks.yml File...
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Initializing config: child.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: child.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Config initialized: child.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Initializing config: repair.vanilla.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: repair.vanilla.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Config initialized: repair.vanilla.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Initializing config: salvage.vanilla.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: salvage.vanilla.yml
[13:19:39] [Server thread/INFO]: [mcMMO] [config] Config initialized: salvage.vanilla.yml
[13:19:40] [Server thread/INFO]: [mcMMO] (plugins/mcMMO/flatfile/mcmmo.users) Validating database file..
[13:19:40] [Server thread/INFO]: [mcMMO] Enabling Acrobatics Skills
[13:19:40] [Server thread/INFO]: [mcMMO] Registered subskill: Roll
[13:19:40] [Server thread/INFO]: [mcMMO] [config] Initializing config: experience.yml
[13:19:40] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: experience.yml
[13:19:40] [Server thread/INFO]: [mcMMO] [config] Config initialized: experience.yml
[13:19:40] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[13:19:40] [Server thread/INFO]: [mcMMO] [config] Initializing config: chat.yml
[13:19:40] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: chat.yml
[13:19:40] [Server thread/INFO]: [mcMMO] [config] Config initialized: chat.yml
[13:19:40] [Server thread/INFO]: [dynmap] Enabling dynmap v3.4-beta-3-774
[13:19:40] [Server thread/INFO]: [dynmap] Added 22 custom biome mappings
[13:19:40] [Server thread/INFO]: [dynmap] Using LuckPerms 5.4.25 for access control
[13:19:40] [Server thread/INFO]: [dynmap] Mod Support processing completed`

### '/tardis version' output

n/a, will not load. info above.

**Comment by Chew** [comment]
Latest builds only support 1.19.

```
Could not load 'plugins/TARDISChunkGenerator.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19 at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported
```

**Comment by roracle** [comment]
> Latest builds only support 1.19.
> 
> ```
> Could not load 'plugins/TARDISChunkGenerator.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19 at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported
> ```

Okay I'll have to roll back then. I'm waiting for a lot of other plugins to get updated as well. What were the last 1.18.2 builds?

**Comment by eccentricdevotion** [comment]
Build 2449 was the last one for 1.18.2

**Comment by eccentricdevotion** [comment]
And TARDISChunkGenerator build 164

http://tardisjenkins.duckdns.org:8080/job/TARDISChunkGenerator/164/

**Comment by roracle** [comment]
> And TARDISChunkGenerator build 164
> 
> http://tardisjenkins.duckdns.org:8080/job/TARDISChunkGenerator/164/

Thank you for the info!
