### ISSUE TITLE
Nothing is being Functional

### ISSUE THREAD

**Issue by devan-mysterio** [eccentricdevotion/TARDIS#654]
### Describe the bug

Creating a TARDIS works fine. Moving a tardis works ok. Upgrading your tardis runs into issues.

### To Reproduce

Install and Try for yourself.

### Log files

```
Paste configs or paste.gg link here!
```
[latest (2).log](https://github.com/eccentricdevotion/TARDIS/files/8987557/latest.2.log)

### '/tardis version' output

[26.06 16:43:33] [Server] [INFO] [TARDIS] Server version: git-Paper-39 (MC: 1.19)
[26.06 16:43:33] [Server] [INFO] [TARDIS] TARDIS version: 4.11.0-b2459
[26.06 16:43:33] [Server] [INFO] [TARDIS] TARDISChunkGenerator version: 4.11.0
[26.06 16:43:33] [Server] [INFO] [TARDIS] PlaceholderAPI version: 2.11.1
[26.06 16:43:33] [Server] [INFO] [TARDIS] LibsDisguises version: 10.0.28-SNAPSHOT
[26.06 16:43:33] [Server] [INFO] [TARDIS] floodgate version: 2.1.0-SNAPSHOT
[26.06 16:43:33] [Server] [INFO] [TARDIS] Essentials version: 2.19.5-dev+21-ff80338
[26.06 16:43:33] [Server] [INFO] [TARDIS] WorldGuard version: 7.0.8-SNAPSHOT+2201-6efdb10
[26.06 16:43:33] [Server] [INFO] [TARDIS] CoreProtect version: 21.2
[26.06 16:43:33] [Server] [INFO] [TARDIS] Multiverse-Core version: 4.3.1-b861
[26.06 16:43:33] [Server] [INFO] [TARDIS] GriefPrevention version: 16.18
[26.06 16:43:33] [Server] [INFO] [TARDIS] Checking for new TARDIS builds...
[26.06 16:43:33] [Multicraft] devan_mysterio ran command: tardis version
[26.06 16:43:34] [Server] [INFO] [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
You need to update to a 1.19 compatible build...

**Comment by Chew** [comment]
Yeah he said he ran `/tardis update_plugins` then all was well.

**Comment by devan-mysterio** [comment]
Now TARDIS is stuck materialising 
[27.06 14:55:57] [Server] [INFO] devan_mysterio issued server command: /tt rebuild
[27.06 14:55:58] [Server] [WARN] [TARDIS] Task #9230 for TARDIS v4.11.0-b2459 generated an exception
[27.06 14:55:58] [Server] java.lang.NullPointerExceptionCannot invoke "org.bukkit.Location.getBlock()" because "l" is null
[27.06 14:55:58] [Server] 	at me.eccentric_nz.TARDIS.utility.TARDISBlockSetters.setBlock(TARDISBlockSetters.java:44) ~[TARDIS.jar:?]
[27.06 14:55:58] [Server] 	at me.eccentric_nz.TARDIS.destroyers.TARDISDeinstantPreset.lambda$instaDestroyPreset$1(TARDISDeinstantPreset.java:182) ~[TARDIS.jar:?]
[27.06 14:55:58] [Server] 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
[27.06 14:55:58] [Server] 	at me.eccentric_nz.TARDIS.destroyers.TARDISDeinstantPreset.instaDestroyPreset(TARDISDeinstantPreset.java:182) ~[TARDIS.jar:?]
[27.06 14:55:58] [Server] 	at me.eccentric_nz.TARDIS.builders.TARDISPresetBuilderFactory.buildPreset(TARDISPresetBuilderFactory.java:142) ~[TARDIS.jar:?]
[27.06 14:55:58] [Server] 	at me.eccentric_nz.TARDIS.commands.tardis.TARDISRebuildCommand.lambda$rebuildPreset$0(TARDISRebuildCommand.java:133) ~[TARDIS.jar:?]
[27.06 14:55:58] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-39]
[27.06 14:55:58] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]


[27.06 14:57:50] [Multicraft] devan_mysterio ran command: tardis version
[27.06 14:57:50] [Server] [INFO] [TARDIS] Server version: git-Paper-39 (MC: 1.19)
[27.06 14:57:50] [Server] [INFO] [TARDIS] TARDIS version: 4.11.0-b2459
[27.06 14:57:50] [Server] [INFO] [TARDIS] TARDISChunkGenerator version: 4.11.0
[27.06 14:57:50] [Server] [INFO] [TARDIS] PlaceholderAPI version: 2.11.1
[27.06 14:57:50] [Server] [INFO] [TARDIS] LibsDisguises version: 10.0.28-SNAPSHOT
[27.06 14:57:50] [Server] [INFO] [TARDIS] floodgate version: 2.1.0-SNAPSHOT
[27.06 14:57:50] [Server] [INFO] [TARDIS] Essentials version: 2.19.5-dev+21-ff80338
[27.06 14:57:50] [Server] [INFO] [TARDIS] WorldGuard version: 7.0.8-SNAPSHOT+2201-6efdb10
[27.06 14:57:50] [Server] [INFO] [TARDIS] CoreProtect version: 21.2
[27.06 14:57:50] [Server] [INFO] [TARDIS] Multiverse-Core version: 4.3.1-b861
[27.06 14:57:50] [Server] [INFO] [TARDIS] GriefPrevention version: 16.18
[27.06 14:57:50] [Server] [INFO] [TARDIS] Checking for new TARDIS builds...
[27.06 14:57:51] [Server] [INFO] [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
It is unlikely that the TARDIS was created properly when you had the incorrect plugin version. Do a clean install and make a new TARDIS.

**Comment by devan-mysterio** [comment]
Ok I deleted TARDIS.DB all worlds associated and the datapack leaving unmodified server files
