### ISSUE TITLE
TARDIS fails when the world the TARDIS was in is not loaded

### ISSUE THREAD

**Issue by devan-mysterio** [eccentricdevotion/TARDIS#671]
### Describe the bug

So i'm running 1.19.2 Paper https://i.imgur.com/Hk8tmde.png
and I'm running present version of the plugins https://i.imgur.com/wqyM4VF.png

When I go to do /tt rebuild or travel it doesn't do anything, just an error

### To Reproduce

Install
Start
Place Seed
use key
go in
activate it
change chameleon circuit or travel
error

### Log files

```
[29.10 16:29:35] [Server] [WARN] [TARDIS] Task #16661 for TARDIS v4.11.1-b2471 generated an exception
[29.10 16:29:35] [Server] java.lang.NullPointerExceptionCannot invoke "org.bukkit.Location.getBlock()" because "l" is null
[29.10 16:29:35] [Server] 	at me.eccentric_nz.TARDIS.utility.TARDISBlockSetters.setBlock(TARDISBlockSetters.java:44) ~[TARDIS.jar:?]
[29.10 16:29:35] [Server] 	at me.eccentric_nz.TARDIS.destroyers.TARDISDeinstantPreset.lambda$instaDestroyPreset$1(TARDISDeinstantPreset.java:183) ~[TARDIS.jar:?]
[29.10 16:29:35] [Server] 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
[29.10 16:29:35] [Server] 	at me.eccentric_nz.TARDIS.destroyers.TARDISDeinstantPreset.instaDestroyPreset(TARDISDeinstantPreset.java:183) ~[TARDIS.jar:?]
[29.10 16:29:35] [Server] 	at me.eccentric_nz.TARDIS.builders.TARDISPresetBuilderFactory.buildPreset(TARDISPresetBuilderFactory.java:142) ~[TARDIS.jar:?]
[29.10 16:29:35] [Server] 	at me.eccentric_nz.TARDIS.commands.tardis.TARDISRebuildCommand.lambda$rebuildPreset$0(TARDISRebuildCommand.java:133) ~[TARDIS.jar:?]
[29.10 16:29:35] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-246]
[29.10 16:29:35] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### '/tardis version' output

[29.10 16:33:46] [Server] [INFO] [TARDIS] Server version: git-Paper-246 (MC: 1.19.2)
[29.10 16:33:46] [Server] [INFO] [TARDIS] TARDIS version: 4.11.1-b2471
[29.10 16:33:46] [Server] [INFO] [TARDIS] TARDISChunkGenerator version: 4.11.0
[29.10 16:33:46] [Server] [INFO] [TARDIS] PlaceholderAPI version: 2.11.1
[29.10 16:33:46] [Server] [INFO] [TARDIS] LibsDisguises version: 10.0.31-SNAPSHOT
[29.10 16:33:46] [Server] [INFO] [TARDIS] floodgate version: 2.2.0-SNAPSHOT (b70-6e2c19f)
[29.10 16:33:46] [Server] [INFO] [TARDIS] dynmap version: 3.4-828
[29.10 16:33:46] [Server] [INFO] [TARDIS] WorldGuard version: 7.0.8-SNAPSHOT+2201-6efdb10
[29.10 16:33:46] [Server] [INFO] [TARDIS] CoreProtect version: 21.2
[29.10 16:33:46] [Server] [INFO] [TARDIS] TARDISWeepingAngels version: 3.6.3
[29.10 16:33:46] [Server] [INFO] [TARDIS] LWC version: 2.2.8-f367129
[29.10 16:33:46] [Server] [INFO] [TARDIS] Multiverse-Core version: 4.3.1-b861
[29.10 16:33:46] [Server] [INFO] [TARDIS] Checking for new TARDIS builds...
[29.10 16:33:47] [Server] [INFO] [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
Left your TARDIS in a world that no longer exists / is not loaded on the server?

Attach TARDIS.db

**Comment by devan-mysterio** [comment]
I didn't leave it in a world thats unloaded even i deleted the tardis and regenerated it and still nothing

**Comment by eccentricdevotion** [comment]
Still need to see your TARDIS.db, and ideally a server startup log

**Comment by devan-mysterio** [comment]
[2022-10-29-9.log](https://github.com/eccentricdevotion/TARDIS/files/9894755/2022-10-29-9.log)
how do i upload the tardis.db it's not working

**Comment by eccentricdevotion** [comment]
Zip the file first, then just drag and drop

**Comment by devan-mysterio** [comment]
[TARDISDB FILE.zip](https://github.com/eccentricdevotion/TARDIS/files/9894762/TARDISDB.FILE.zip)

**Comment by eccentricdevotion** [comment]
`Invalid/Unloaded world for: '-923.0,116.0,-749.0,0.0,0.0,Runic-NetworkV1' location!`

There are also records for a `island_normal_world` which is not loaded

**Comment by devan-mysterio** [comment]
What do i do about it?

**Comment by eccentricdevotion** [comment]
Load the worlds

**Comment by devan-mysterio** [comment]
they don't exist

**Comment by eccentricdevotion** [comment]
They obviously did at some stage...
You could edit the database and delete the records for locations  with non-existent worlds

`DELETE FROM blocks WHERE loacation LIKE '%Runic-NetworkV1%';`
`DELETE FROM blocks WHERE loacation LIKE '%island_normal_world%'`

Use _DB Browser for SQLite_ or some other app

**Comment by devan-mysterio** [comment]
Idk how

**Comment by eccentricdevotion** [comment]
Try build 2472

**Comment by devan-mysterio** [comment]
That worked awesome thank you!
