### ISSUE TITLE
Not able to see recipes or craft plugin items

### ISSUE THREAD

**Issue by CorruptTraveler** [eccentricdevotion/TARDIS#72]
When I launch the server, this WARN pops up:.

"[04:07:15 ERROR]: Error occurred while enabling TARDIS v3.8.2-b1677 (Is it up to date?)
java.lang.IllegalArgumentException: key
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72) ~[craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at me.eccentric_nz.TARDIS.recipes.TARDISShapedRecipe.makeRecipe(TARDISShapedRecipe.java:111) ~[?:?]
	at me.eccentric_nz.TARDIS.recipes.TARDISShapedRecipe.lambda$addShapedRecipes$8(TARDISShapedRecipe.java:72) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_172]
	at me.eccentric_nz.TARDIS.recipes.TARDISShapedRecipe.addShapedRecipes(TARDISShapedRecipe.java:71) ~[?:?]
	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:319) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-ab13683]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]"

And when I type in "/trecipe list" or do something like "/trecipe tardis budget" It does not show me the recipe, rather it says, "/trecipe [item] - use /trecipe list - to see all the items"

I also can't craft the items, even though I'm doing the recipe for it correctly.

**Comment by eccentricdevotion** [comment]
Delete recipes.yml and let it regenerate, then try again

**Comment by eccentricdevotion** [comment]
Spigot has made a change to NamespacedKey parsing - looks like the key needs to be lowercase...
Fixed in build 1716 on the TARDIS Jenkins server, make sure you grab the latest TARDISChunkGenerator from there too, if you update.
Alternatively downgrade Spigot to an earlier build.

**Comment by eccentricdevotion** [comment]
0900ef4

**Comment by CorruptTraveler** [comment]
Thx, helped a lot!
