### ISSUE TITLE
Can't interact with specific player's TARDIS at all

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#729]
### Describe the bug

One player on our server can't enter or use their TARDIS at all anymore, and I can't get into it or move it either.

The error attached is printed any time we try (this one is from trying to summon it with /tardisremote). I've had a look at the database where that error's coming from and their `chameleon_demat` is just set to `ITEM:` and nothing else, so no idea how they've managed that.

We're not sure what they did, all they can think of is that they use the junk TARDIS at some point.

### To Reproduce

Unsure

### Log files

```
[Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tremote' in plugin TARDIS v5.0.0-b2645
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003) ~[paper-1.20.1.jar:git-Paper-62]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-62]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-62]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at me.eccentric_nz.TARDIS.database.resultset.ResultSetTardis.resultSet(ResultSetTardis.java:150) ~[TARDIS-b2645.jar:?]
	at me.eccentric_nz.TARDIS.commands.remote.TARDISRemoteCommands.onCommand(TARDISRemoteCommands.java:79) ~[TARDIS-b2645.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

### '/tardis version' output

```
[TARDIS] Server version: git-Paper-62 (MC: 1.20.1)
[TARDIS] TARDIS version: 5.0.0-b2645
[TARDIS] LibsDisguises version: 10.0.37
[TARDIS] Vault version: 1.7.3-b131
[TARDIS] floodgate version: 2.2.2-SNAPSHOT (b59-2278589)
[TARDIS] dynmap version: 3.6-beta-2-894
[TARDIS] WorldBorder version: 1.9.10 (beta)
[TARDIS] Multiverse-Core version: 4.3.2-SNAPSHOT-b870
[TARDIS] WorldGuard version: 7.1.0-SNAPSHOT+2251-8cbce96
[TARDIS] CoreProtect version: 21.3
```

**Comment by eccentricdevotion** [comment]
You could just edit the database and change `ITEM:` to `FACTORY`, but I'll add a check so it shouldn't happen again...

**Comment by DrPepplies** [comment]
I didn't want to risk editing the database, wasn't sure what the right thing was. I've updated now and their TARDIS is working, thank you!
