### ISSUE TITLE
NullPointerException from time rotor

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#733]
### Describe the bug

A NullPointerException error started spamming the console, and didn't stop until I used `/tardis abort` to stop the task.

### To Reproduce

No idea what caused it, there are no obvious commands in the log before the error started of anyone interacting with TARDIS. Lots of people were on at the time so couldn't figure out even who's TARDIS it was coming from.

### Log files

```
[Server thread/WARN]: [TARDIS] Task #12012458 for TARDIS v5.0.0-b2666 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setCustomModelData(java.lang.Integer)" because "im" is null
	at me.eccentric_nz.TARDIS.builders.TimeRotorAnimation.run(TimeRotorAnimation.java:22) ~[TARDIS-b2666.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-98]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-98]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### '/tardis version' output

```
[TARDIS] Server version: git-Paper-98 (MC: 1.20.1)
[TARDIS] TARDIS version: 5.0.0-b2666
[TARDIS] LibsDisguises version: 10.0.37
[TARDIS] Vault version: 1.7.3-b131
[TARDIS] floodgate version: 2.2.2-SNAPSHOT (b59-2278589)
[TARDIS] dynmap version: 3.6-beta-2-894
[TARDIS] WorldBorder version: 1.9.10 (beta)
[TARDIS] Multiverse-Core version: 4.3.2-SNAPSHOT-b870
[TARDIS] WorldGuard version: 7.1.0-SNAPSHOT+2251-8cbce96
[TARDIS] CoreProtect version: 21.3
```
Not super up to date but only a little behind.

**Comment by DrPepplies** [comment]
Have been running the new build and not seen this error again since, so safe to say it's fixed. Thanks!
