### ISSUE TITLE
Custom glass seed breaks when placing and doesn't turn into working seed

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#735]
### Describe the bug

We have a custom console that uses glass as it's seed block, and one that uses red stained glass.

When placing them in the newer TARDIS versions, it logs out this error. The block turns into a barrier but no custom texture appears (so it stays as a barrier), and clicking it with the key doesn't do anything.

Our other ones that use other non-glass blocks still work okay.

If the solution is that we can't use glass as custom seeds anymore that's fine we can change them, just thought I'd check.

### To Reproduce

Put this in `custom_consoles.yml`, then craft the seed with glass, and place it.

```
GLASS_CONSOLE:
  enabled: true
  schematic: glass_console
  seed: GLASS
  has_beacon: false
  description: Glass Console
  has_lanterns: false
  lights: LAMP
```

### Log files

```
[Server thread/ERROR]: Could not pass event BlockPlaceEvent to TARDIS v5.0.0-b2666
java.lang.NullPointerException: Cannot invoke "me.eccentric_nz.TARDIS.customblocks.TARDISDisplayItem.getMaterial()" because "tdi" is null
	at me.eccentric_nz.TARDIS.customblocks.TARDISDisplayItemUtils.setSeed(TARDISDisplayItemUtils.java:215) ~[TARDIS-b2666.jar:?]
	at me.eccentric_nz.TARDIS.listeners.TARDISSeedBlockListener.onSeedBlockPlace(TARDISSeedBlockListener.java:82) ~[TARDIS-b2666.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor706.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-98]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-98]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-98]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:421) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:413) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:597) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-98]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-98]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### '/tardis version' output

[TARDIS] Server version: git-Paper-98 (MC: 1.20.1)
[TARDIS] TARDIS version: 5.0.0-b2666
[TARDIS] LibsDisguises version: 10.0.37
[TARDIS] Vault version: 1.7.3-b131
[TARDIS] floodgate version: 2.2.2-SNAPSHOT (b59-2278589)
[TARDIS] dynmap version: 3.6-beta-2-894
[TARDIS] WorldBorder version: 1.9.10 (beta)
[TARDIS] Multiverse-Core version: 4.3.2-SNAPSHOT-b870
[TARDIS] WorldGuard version: 7.1.0-SNAPSHOT+2251-8cbce96
[TARDIS] CoreProtect version: 21.3

Quite a few builds behind I know but from the changelog didn't think the new builds changed this at all.

**Comment by DrPepplies** [comment]
Actually just noticed it also happens with one that uses smooth quartz as its seed so maybe not just glass?

**Comment by eccentricdevotion** [comment]
Build available

**Comment by DrPepplies** [comment]
New build fixes it, thanks!
