### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#75]
When I load the server, i am getting the following errors

```
[13:21:20] [Server thread/INFO]: [TARDIS] Enabling TARDIS v4.0.0-b1723
[13:21:20] [Server thread/INFO]: [0;33;22m[TARDIS][m The TARDIS Key recipe result (recipes.yml) does not match the configured key preference (config.yml)[m
[13:21:20] [Server thread/INFO]: [0;33;22m[TARDIS][m Loading language: ENGLISH[m
[13:21:20] [Server thread/INFO]: [0;33;22m[TARDIS][m Removed 'TARDIS_TimeVortex from config.yml[m
[13:21:20] [Server thread/INFO]: [0;33;22m[TARDIS][m Default world specified, but it doesn't exist! Trying to create it now...[m
```

Why is it removing and adding TARDIS_TimeVortex every time?

```
[13:21:23] [Server thread/ERROR]: Error occurred while enabling TARDIS v4.0.0-b1723 (Is it up to date?)
java.lang.IllegalArgumentException: Could not parse data: 0
	at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.newData(CraftBlockData.java:437) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1808) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1801) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at me.eccentric_nz.TARDIS.database.ResultSetBlocks.resultSet(ResultSetBlocks.java:102) ~[?:?]
	at me.eccentric_nz.TARDIS.files.TARDISBlockLoader.loadProtectBlocks(TARDISBlockLoader.java:56) ~[?:?]
	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:272) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:0' at position 0: <--[HERE]


[13:23:09] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TARDIS v4.0.0-b1723
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PlayerList.onPlayerJoin(PlayerList.java:343) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PlayerList.a(PlayerList.java:163) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.LoginListener.b(LoginListener.java:150) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.listeners.TARDISJoinListener.onJoin(TARDISJoinListener.java:178) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	... 14 more
[13:23:10] [Server thread/INFO]: L0rd_Aragorn[/173.216.5.139:55132] logged in with entity id 120 at ([world]-1564.933015813921, 65.0, 161.61929032029462)
[13:23:10] [Server thread/INFO]: [0;33;1m :[ L0rd_Aragorn has joined. ]:[m
[13:23:19] [Server thread/INFO]: L0rd_Aragorn issued server command: /tadmin enter L0rd_Aragorn
[13:23:19] [pool-13-thread-1/INFO]: [0;33;1mRegion 'tardis_l0rd_aragorn' updated with new members.[m
[13:23:43] [Timer-2/INFO]: [WorldGuard] Region data changes made in 'TARDIS_TimeVortex' have been background saved
[13:24:00] [Server thread/INFO]: L0rd_Aragorn issued server command: /tardis rebuild
[13:24:04] [Server thread/INFO]: L0rd_Aragorn issued server command: /tadmin enter L0rd_Aragorn
[13:24:04] [pool-13-thread-1/INFO]: [0;33;1mRegion 'tardis_l0rd_aragorn' updated with new members.[m
[13:24:13] [Timer-2/INFO]: [WorldGuard] Region data changes made in 'TARDIS_TimeVortex' have been background saved
[13:24:26] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to TARDIS v4.0.0-b1723
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:888) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1910) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.artron.TARDISCondenserListener.onChestClose(TARDISCondenserListener.java:123) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	... 16 more
[13:24:53] [Server thread/INFO]: L0rd_Aragorn has made the advancement [Bring Home the Beacon]
[13:25:04] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to TARDIS v4.0.0-b1723
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:888) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1910) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.eccentric_nz.TARDIS.artron.TARDISCondenserListener.onChestClose(TARDISCondenserListener.java:123) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-3b8f5be]
	... 16 more
[13:25:36] [Server thread/INFO]: L0rd_Aragorn issued server command: /tardis rebuild
```

It won't let me condense anything

**Comment by eccentricdevotion** [comment]
Until it enables properly, its going to throw errors all over the show...
Can you attach/send me your pre 1.13 TARDIS v4 database?

**Comment by eccentricdevotion** [comment]
Multiverse not loading TARDIS_TimeVortex properly?

**Comment by ccattell** [comment]
we do not have multiverse

**Comment by ccattell** [comment]
[TARDIS.zip](https://github.com/eccentricdevotion/TARDIS/files/2242931/TARDIS.zip)

**Comment by eccentricdevotion** [comment]
Are you using another multi-world plugin? You'll need one to load any worlds that aren't the default set in server.properties. TARDIS can create the worlds, but it won't load them after a restart (it leaves that to Multiverse and the like).

Can you check the config.yml file and set `conversions.block_materials` to `false` (if it's not already)?

**Comment by eccentricdevotion** [comment]
Seems to be an empty database...

**Comment by ccattell** [comment]
oh, my bad, lol we are using mysql... hold on a sec

**Comment by eccentricdevotion** [comment]
Hmm, I still need to check MySQL functionality, it'll have to wait till after work...

**Comment by eccentricdevotion** [comment]
There's a new build with a couple of changes on the Jenkins server that you can try...

**Comment by ccattell** [comment]
[mcnovus.zip](https://github.com/eccentricdevotion/TARDIS/files/2242976/mcnovus.zip)

**Comment by ccattell** [comment]
ok ill check it out

**Comment by ccattell** [comment]
ok, whatever you or I did has fixed the issue, no errors on load anymore, and i can condense materials again

**Comment by eccentricdevotion** [comment]
Fixed a whole bunch of data conversion errors when using MySQL database or updating from an early TARDIS version.
Build 1726 or higher.
Might want to set some conversions to false:
```
conversions:
  player_prefs_materials: false
  ars_materials: false
  condenser_materials: false
  block_materials: false
```

**Comment by ccattell** [comment]
will the conversion of the database mess up the live server with the 3.8 TARDIS plugin we have there?

**Comment by eccentricdevotion** [comment]
Yes, the v3.8 data uses ids and data which no longer exists in 1.13, so v4.0 converts that data to Materials / BlockData
