### ISSUE TITLE
Errors on server restart

### ISSUE THREAD

**Issue by srtoys** [eccentricdevotion/TARDIS#76]
My server is running Spigot 1.13

Running the following Tardis versions
TARDIS4.0.1-b1732
TARDISChunkGenerator4.0.1-b44

When restart the server get the following errors:
If I delete the config.yml and restart I get no errors and the plugin works ok
until I restart the server again.

[14:28:27 INFO]: [TARDIS] Enabling TARDIS v4.0.1-b1732
[14:28:27 INFO]: [TARDIS] Loading language: ENGLISH
[14:28:27 INFO]: [TARDIS] Added 149 new items to config
[14:28:27 INFO]: [TARDIS] Added 'world1.13' to config. To exclude this world run: /tardisadmin exclude world1.13
[14:28:27 INFO]: [TARDIS] Removed 'world1' from config.yml
[14:28:27 ERROR]: Error occurred while enabling TARDIS v4.0.1-b1732 (Is it up to date?)
me.eccentric_nz.TARDIS.JSON.JSONException: JSONArray[0] is not a number.
        at me.eccentric_nz.TARDIS.JSON.JSONArray.getInt(JSONArray.java:237) ~[?:?]
        at me.eccentric_nz.TARDIS.ARS.ARSConverter.convertARS(ARSConverter.java:70) ~[?:?]
        at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:221) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-69774b3-80c43fc]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by eccentricdevotion** [comment]
Check config, make sure `conversions.ars_materials` is set to `true`

**Comment by srtoys** [comment]
That took care of the errors, thanks, love your plugin keep up the great work.

**Comment by eccentricdevotion** [comment]
Note to self: this is related to the default config (`Plugin#saveDefaultConfig()`) not being saved to disk properly on first run of the plugin.

**Comment by eccentricdevotion** [comment]
Should be fixed by  https://github.com/eccentricdevotion/TARDIS/commit/a8d98a887c884bde0a029339527e8c16c17ec834
