### ISSUE TITLE
Problem in worldguard

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#77]
just noticed an issue between tardis and the latest worldguard build

```
[21:29:16 INFO]: frododog issued server command: /tardis comehere
[21:29:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tardis' in plugin TARDIS v4.0.2-b1743
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.ApplicableRegionSet.canBuild(Lcom/sk89q/worldguard/LocalPlayer;)Z
        at me.eccentric_nz.TARDIS.utility.TARDISWorldGuardUtils.canLand(TARDISWorldGuardUtils.java:101) ~[?:?]
        at me.eccentric_nz.TARDIS.travel.TARDISPluginRespect.getRespect(TARDISPluginRespect.java:91) ~[?:?]
        at me.eccentric_nz.TARDIS.commands.tardis.TARDISComehereCommand.doComeHere(TARDISComehereCommand.java:86) ~[?:?]
        at me.eccentric_nz.TARDIS.commands.tardis.TARDISCommands.onCommand(TARDISCommands.java:115) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-2b0e71c-c0df4b8]
        ... 15 more
```

**Comment by ccattell** [comment]
we are using build #1738 of worldguard

**Comment by eccentricdevotion** [comment]
Try build #1744

**Comment by ccattell** [comment]
Have I ever told you that you rock???  New build fixed that right up!

**Comment by eccentricdevotion** [comment]
Fixed by 
https://github.com/eccentricdevotion/TARDIS/commit/f27241acd14c7e079bc198f4d85ab1ff79ec279b
