### ISSUE TITLE
Can't craft seed

### ISSUE THREAD

**Issue by User8395** [eccentricdevotion/TARDIS#770]
### Describe the bug

I can't craft a tardis seed

### To Reproduce

1. Get recipe for seed
2. Try to craft seed
3. Ultimately fail

### Screenshots

![image](https://github.com/eccentricdevotion/TARDIS/assets/49075348/0697c8d2-f4f4-48b4-a97f-11312368d068)

### Log files

```
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
System Info: Java 21 (OpenJDK 64-Bit Server VM 21+35) Host: Linux 6.1.61-3-MANJARO-RPI4 (aarch64)
Loading libraries, please wait...
[13:11:46 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:11:46 INFO]: Found new data pack file/bukkit, loading it automatically
[13:11:54 INFO]: Loaded 7 recipes
[13:11:57 INFO]: Starting minecraft server version 1.20.1
[13:11:57 INFO]: Loading properties
[13:11:57 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
[13:11:59 INFO]: Server Ping Player Sample Count: 12
[13:11:59 INFO]: Using 4 threads for Netty based IO
[13:12:00 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[13:12:00 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[13:12:02 INFO]: Default game type: SURVIVAL
[13:12:02 INFO]: Generating keypair
[13:12:02 INFO]: Starting Minecraft server on *:25565
[13:12:02 INFO]: Using epoll channel type
[13:12:02 INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[13:12:02 INFO]: Paper: Using OpenSSL (Linux aarch64) cipher from Velocity.
[13:12:04 INFO]: [SpigotLibraryLoader] [TARDIS] Loading 1 libraries... please wait
[13:12:05 INFO]: [SpigotLibraryLoader] Downloading https://repo.maven.apache.org/maven2/org/jsoup/jsoup/1.16.1/jsoup-1.16.1.pom
[13:12:05 INFO]: [SpigotLibraryLoader] Downloading https://repo.maven.apache.org/maven2/org/jsoup/jsoup/1.16.1/jsoup-1.16.1.jar
[13:12:05 INFO]: [SpigotLibraryLoader] [TARDIS] Loaded library /home/pi/minecraft/libraries/org/jsoup/jsoup/1.16.1/jsoup-1.16.1.jar
[13:12:05 INFO]: [floodgate] Loading server plugin floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[13:12:08 INFO]: [floodgate] Took 2,772ms to boot Floodgate
[13:12:08 INFO]: [ViaVersion] Loading server plugin ViaVersion v4.9.2
[13:12:08 INFO]: [ViaVersion] ViaVersion 4.9.2 is now loaded. Registering protocol transformers and injecting...
[13:12:10 INFO]: [ViaVersion] Loading block connection mappings ...
[13:12:11 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[13:12:11 INFO]: [Geyser-Spigot] Loading server plugin Geyser-Spigot v2.2.0-SNAPSHOT
[13:12:13 INFO]: [Geyser-Spigot] Loading extensions...
[13:12:13 INFO]: [Geyser-Spigot] Loaded 0 extension(s)
[13:12:13 INFO]: [TARDIS] Loading server plugin TARDIS v5.1.0-b2704
[13:12:13 INFO]: Preparing level "world"
[13:13:00 INFO]: Preparing start region for dimension minecraft:overworld
[13:13:01 INFO]: Time elapsed: 558 ms
[13:13:01 INFO]: Preparing start region for dimension minecraft:the_nether
[13:13:01 INFO]: Time elapsed: 346 ms
[13:13:01 INFO]: Preparing start region for dimension minecraft:the_end
[13:13:01 INFO]: Time elapsed: 326 ms
[13:13:01 INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[13:13:04 INFO]: [ViaVersion] Enabling ViaVersion v4.9.2
[13:13:04 INFO]: [ViaVersion] ViaVersion detected server version: 1.20/1.20.1 (763)
[13:13:05 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.2.0-SNAPSHOT
[13:13:05 INFO]: [TARDIS] Enabling TARDIS v5.1.0-b2704
[13:13:07 INFO]:   ‗‗≡‗‗
[13:13:07 INFO]:   |‡|‡|    ▀█▀ ▄▀▄ █▀▄ █▀▄ █ ▄▀▀
[13:13:07 INFO]:   |¤|•|     █  █▀█ █▀▄ █▄▀ █ ▄▄▀
[13:13:07 INFO]:   | | |    May contain bugs!
[13:13:07 INFO]:   ═════
[13:13:08 INFO]: [TARDIS] Created language directory.
[13:13:08 INFO]: [TARDIS] Loading language: ENGLISH
[13:13:08 INFO]: [TARDIS] Added 2 new items to config
[13:13:08 INFO]: [TARDIS Helper] Defaulted to GameMode.SURVIVAL, World.Environment.NORMAL, WorldType.NORMAL
[13:13:08 INFO]: [TARDIS] Added 'world' to planets.yml. To exclude this world from time travel run: /tardisadmin exclude world
[13:13:08 INFO]: [TARDIS Helper] Defaulted to GameMode.SURVIVAL, World.Environment.NORMAL, WorldType.NORMAL
[13:13:08 INFO]: [TARDIS] Added 'world_nether' to planets.yml. To exclude this world from time travel run: /tardisadmin exclude world_nether
[13:13:08 INFO]: [TARDIS Helper] Defaulted to GameMode.SURVIVAL, World.Environment.NORMAL, WorldType.NORMAL
[13:13:08 INFO]: [TARDIS] Added 'world_the_end' to planets.yml. To exclude this world from time travel run: /tardisadmin exclude world_the_end
[13:13:08 INFO]: [TARDIS] Attempting to load world: 'TARDIS_TimeVortex'
[13:13:08 ERROR]: No key layers in MapLike[{}]
[13:13:08 INFO]: Preparing start region for dimension minecraft:tardis_timevortex
[13:13:09 INFO]: Time elapsed: 283 ms
[13:13:12 INFO]: [TARDIS] Created user_schematics directory.
[13:13:16 INFO]: [TARDIS] Created books directory.
[13:13:16 INFO]: [TARDIS WARNING] Attempting to create TARDIS advancement directories...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the craft.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (craft.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the defender.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (defender.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the energy.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (energy.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the farm.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (farm.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the friends.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (friends.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the kill.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (kill.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the rooms.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (rooms.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the root.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (root.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the tardis.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (tardis.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the travel.json TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (travel.json) to the correct directory...
[13:13:16 INFO]: [TARDIS WARNING] Could not find the pack.mcmeta TARDIS advancement file...
[13:13:16 INFO]: [TARDIS WARNING] Attempting to copy advancement file (pack.mcmeta) to the correct directory...
[13:13:17 INFO]: [Geyser-Spigot] ******************************************
[13:13:17 INFO]: [Geyser-Spigot] 
[13:13:17 INFO]: [Geyser-Spigot] Loading Geyser version 2.2.0-SNAPSHOT (git-master-cdb8ab3)
[13:13:17 INFO]: [Geyser-Spigot] 
[13:13:17 INFO]: [Geyser-Spigot] ******************************************
[13:13:35 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[13:13:35 INFO]: [Geyser-Spigot] Done (17.956s)! Run /geyser help for help!
[13:13:36 WARN]: [Geyser-Spigot] Missing MC locale file: en_us
[13:13:36 INFO]: [Geyser-Spigot] Downloading Minecraft JAR to extract required files, please wait... (this may take some time depending on the speed of your internet connection)
[13:13:36 INFO]: Running delayed init tasks
[13:13:36 INFO]: Done (99.380s)! For help, type "help"
[13:13:36 INFO]: Timings Reset
[13:13:36 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[13:13:37 INFO]: com.mojang.authlib.GameProfile@1bb20fb1[id=<null>,name=User8395,properties={},legacy=false] (/192.168.1.206:57450) lost connection: Disconnected
[13:13:39 INFO]: There is a new TARDIS build! You are using #2704, the latest build is #2755!
[13:13:39 INFO]: Visit http://tardisjenkins.duckdns.org:8080/job/TARDIS/ or run the '/tardisadmin update_plugins' command
[13:13:40 INFO]: [Geyser-Spigot] Minecraft JAR has been successfully downloaded and loaded!
[13:13:46 INFO]: [TARDIS] Custom advancements not found, forcing server advancements to reload!
[13:13:48 INFO]: Loaded 7 recipes
[13:13:52 WARN]: Can't keep up! Is the server overloaded? Running 5787ms or 115 ticks behind
[13:14:36 INFO]: UUID of player User8395 is d12575fd-cdaa-45e8-9d31-75f3182c41da
[13:14:37 INFO]: User8395 joined the game
[13:14:37 INFO]: User8395[/192.168.1.206:48572] logged in with entity id 21 at ([world]-71.5, 71.0, 72.5)
> op User8395
[13:16:25 INFO]: Made User8395 a server operator
[13:16:30 INFO]: User8395 issued server command: /gamemode creative
[13:16:30 INFO]: [User8395: Set own game mode to Creative Mode]
[13:16:56 INFO]: User8395 issued server command: /tardis
[13:17:19 WARN]: Can't keep up! Is the server overloaded? Running 5046ms or 100 ticks behind
[13:18:43 INFO]: User8395 issued server command: /tardisrecipe
[13:24:11 INFO]: <User8395> how do I make a TARDIS?
[13:24:11 WARN]: [TARDIS] Task #2657 for TARDIS v5.1.0-b2704 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
        at me.eccentric_nz.TARDIS.howto.TARDISSeedsInventory.getItemStack(TARDISSeedsInventory.java:70) ~[TARDIS.jar:?]
        at me.eccentric_nz.TARDIS.howto.TARDISSeedsInventory.<init>(TARDISSeedsInventory.java:47) ~[TARDIS.jar:?]
        at me.eccentric_nz.TARDIS.listeners.TARDISChatListener.lambda$handleChat$0(TARDISChatListener.java:109) ~[TARDIS.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[13:24:33 INFO]: User8395 issued server command: /tardisrecipe seed twelfth
[13:25:01 INFO]: User8395 issued server command: /tardisrecipe seed twelfth
[13:25:43 INFO]: User8395 issued server command: /tardis version
[13:26:37 INFO]: <User8395> “how do I make a TARDIS?”
[13:26:41 INFO]: <User8395> how do I make a TARDIS?
[13:27:19 INFO]: User8395 issued server command: /tardisbook
[13:27:32 INFO]: User8395 issued server command: /tardisrecipe seed
[13:27:35 INFO]: User8395 issued server command: /tardisrecipe seed twelfth
> give User8395 minecraft:iron_block
[13:30:36 INFO]: Gave 1 [Block of Iron] to User8395
```

### '/tardis version' output

```
> tardis version
[13:32:58 INFO]: [TARDIS] Server version: git-Paper-196 (MC: 1.20.1)
[13:32:58 INFO]: [TARDIS] TARDIS version: 5.1.0-b2704
[13:32:58 INFO]: [TARDIS] floodgate version: 2.2.2-SNAPSHOT (b85-71acc6c)
[13:32:58 INFO]: [TARDIS] Checking for new TARDIS builds...
[13:32:58 INFO]: [TARDIS] You are 51 builds behind! Type /tadmin update_pluginsto update!
```

**Comment by eccentricdevotion** [comment]
Fixed "how do I make a TARDIS?"
25e425f
