### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#78]
Not sure whats causing this one
```
[16:30:51] [Server thread/INFO]: [0;33;22m[TARDIS][m Loading language: ENGLISH[m
[16:30:51] [Server thread/ERROR]: Error occurred while enabling TARDIS v4.0.3-b1750 (Is it up to date?)
java.lang.NullPointerException: null
	at me.eccentric_nz.TARDIS.database.ResultSetBlocks.resultSet(ResultSetBlocks.java:102) ~[?:?]
	at me.eccentric_nz.TARDIS.files.TARDISBlockLoader.loadProtectBlocks(TARDISBlockLoader.java:56) ~[?:?]
	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:276) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by eccentricdevotion** [comment]
Can you post a database dump of your blocks table

**Comment by ccattell** [comment]
[TARDIS_blocks.zip](https://github.com/eccentricdevotion/TARDIS/files/2316059/TARDIS_blocks.zip)

**Comment by ccattell** [comment]
Thank you sir, that worked perfectly... now if i could just get Towny to update I would have no errors....
