### ISSUE TITLE
Trouble loading map in ARS

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#81]
```
[17:24:46 ERROR]: Could not pass event InventoryClickEvent to TARDIS v4.0.4-b1775
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2142) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: me.eccentric_nz.TARDIS.JSON.JSONException: JSONArray[0] not a string.
        at me.eccentric_nz.TARDIS.JSON.JSONArray.getString(JSONArray.java:293) ~[?:?]
        at me.eccentric_nz.TARDIS.ARS.TARDISARSMethods.getGridFromJSON(TARDISARSMethods.java:107) ~[?:?]
        at me.eccentric_nz.TARDIS.ARS.TARDISARSMethods.loadMap(TARDISARSMethods.java:378) ~[?:?]
        at me.eccentric_nz.TARDIS.ARS.TARDISARSListener.onARSTerminalClick(TARDISARSListener.java:114) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-e3d7b2f]
        ... 15 more
```

**Comment by ccattell** [comment]
I also tried the latest TARDIS version, build 1778 I think, and it has major issues re-materializing, so I had to roll back the version so people could use their TARDIS

**Comment by ccattell** [comment]
still having trouble loading the map in the ARS in build 1818

**Comment by ccattell** [comment]
[13:21:14] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TARDIS v4.0.7-b1818
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2108) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: me.eccentric_nz.TARDIS.JSON.JSONException: JSONArray[0] not a string.
	at me.eccentric_nz.TARDIS.JSON.JSONArray.getString(JSONArray.java:293) ~[?:?]
	at me.eccentric_nz.TARDIS.ARS.TARDISARSMethods.getGridFromJSON(TARDISARSMethods.java:107) ~[?:?]
	at me.eccentric_nz.TARDIS.ARS.TARDISARSMethods.loadMap(TARDISARSMethods.java:378) ~[?:?]
	at me.eccentric_nz.TARDIS.ARS.TARDISARSListener.onARSTerminalClick(TARDISARSListener.java:114) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
	... 15 more

**Comment by eccentricdevotion** [comment]
ARS data still not converted, there shouldn't be any Material ID numbers in the stored JSON
