### ISSUE TITLE
Can't /tardisgive or check recipes of the custom consoles?

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#921]
### Describe the bug

When doing `/tardisgive` or `/tardisrecipe` of any of the new modelled consoles, console throws an error. I'm not entirely sure if this is a plugin bug or a problem with our set up, but our `recipes.yml` is identical to the one in this repo so I don't think it's that?

### To Reproduce

`/tardisgive name cyan-console 1` or `/tardisrecipe cyan-console` for example. Seems to be any of the colored consoles, at least that I've noticed so far.

### Log files

```
[11:33:45 ERROR]: Command exception: /tardisrecipe cyan-console
org.bukkit.command.CommandException: Unhandled exception executing command 'tardisrecipe' in plugin TARDIS v5.7.5-b2992
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ShapedRecipe.getKey()" because "recipe" is null
        at TARDIS-b2992.jar/me.eccentric_nz.TARDIS.commands.TARDISRecipeCommands.showShapedRecipe(TARDISRecipeCommands.java:211) ~[TARDIS-b2992.jar:?]
        at TARDIS-b2992.jar/me.eccentric_nz.TARDIS.commands.TARDISRecipeCommands.onCommand(TARDISRecipeCommands.java:200) ~[TARDIS-b2992.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 26 more
```

### '/tardis version' output

```
[TARDIS] Server version: 1.21.1-77-4ff58c4 (MC: 1.21.1)
[TARDIS] TARDIS version: 5.7.5-b2992
[TARDIS] Vault version: 1.7.3-b131
[TARDIS] dynmap version: 3.7-SNAPSHOT-948
[TARDIS] Multiverse-Core version: 4.3.2-SNAPSHOT-b870
[TARDIS] CoreProtect version: 23.1
[TARDIS] WorldGuard version: 7.0.12+829a4a4
[TARDIS] WorldBorder version: 1.9.10 (beta)
[TARDIS] floodgate version: 2.2.3-SNAPSHOT (b111-3db8e59)
[TARDIS] LibsDisguises version: 10.0.44
[TARDIS] Checking for new TARDIS builds...
[TARDIS] You are running the latest version!
```

**Comment by DrPepplies** [comment]
Same thing appears to happen with `/tgive sonic-blaster`, although that one doesn't error on /trecipe for some reason (just doesn't recognise the recipe)

**Comment by doctormysterio12** [comment]
I have the same with giving myself the consoles
