### ISSUE TITLE
Regeneration throws outOfBoundsException

### ISSUE THREAD

**Issue by Insomniac314** [eccentricdevotion/TARDIS#923]
### Describe the bug

Regeneration does not trigger

### To Reproduce

- enable regeneration module
- allow tardis.regenerate for yourself or another player,
- attempt to trigger regeneration
- exception should be thrown

### Log files

```
[12:01:04 ERROR]: Could not pass event EntityDamageByEntityEvent to TARDIS v5.7.5-b3003
java.lang.ArrayIndexOutOfBoundsException: Index -3 out of bounds for length 16
        at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687) ~[?:?]
        at TARDIS.jar/me.eccentric_nz.tardisregeneration.Regenerator.processPlayer(Regenerator.java:113) ~[TARDIS.jar:?]
        at TARDIS.jar/me.eccentric_nz.tardisregeneration.ElixirOfLifeListener.onPlayerDamage(ElixirOfLifeListener.java:56) ~[TARDIS.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor805.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-128-d348cb8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.effect.HealOrHarmMobEffect.applyInstantenousEffect(HealOrHarmMobEffect.java:39) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.item.PotionItem.finishUsingItem(PotionItem.java:79) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.item.ItemStack.finishUsingItem(ItemStack.java:607) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4087) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:2019) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3931) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2659) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3911) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:835) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:248) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1821) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### '/tardis version' output

```
[12:06:25 INFO]: [TARDIS] Server version: 1.21.1-128-d348cb8 (MC: 1.21.1)
[12:06:25 INFO]: [TARDIS] TARDIS version: 5.7.5-b3003
[12:06:25 INFO]: [TARDIS] Vault version: 1.7.3-b131
[12:06:25 INFO]: [TARDIS] PlaceholderAPI version: 2.11.6
[12:06:25 INFO]: [TARDIS] WorldGuard version: 7.0.12+829a4a4
[12:06:25 INFO]: [TARDIS] Multiverse-Core version: 4.3.1-b861
[12:06:25 INFO]: [TARDIS] GriefPrevention version: 16.18.4
[12:06:25 INFO]: [TARDIS] Essentials version: 2.21.0-dev+121-f7a8f86
[12:06:25 INFO]: [TARDIS] LibsDisguises version: 10.0.44-SNAPSHOT
```

**Comment by eccentricdevotion** [comment]
What is `regenerations` set to in _regeneration.yml_?
