### ISSUE TITLE
Manual Fight does not prompt user for repeater

### ISSUE THREAD

**Issue by Insomniac314** [eccentricdevotion/TARDIS#924]
### Describe the bug

When flightmode is set to manual, no repeater callouts are printed to chat. Could be due to main console being the 3D model type?

### To Reproduce

1. Build TARDIS with type BONE or RUSTIC
2. Set flightmode to manual
3. set destination and hit handbrake

### Log files

```
[20:49:39 WARN]: [TARDIS] Task #5811 for TARDIS v5.7.5-b3006 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.target" is null
        at TARDIS.jar/me.eccentric_nz.TARDIS.flight.TARDISManualFlightRunnable.run(TARDISManualFlightRunnable.java:65) ~[TARDIS.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### '/tardis version' output

[20:56:36 INFO]: [TARDIS] Server version: 1.21.1-128-d348cb8 (MC: 1.21.1)
[20:56:36 INFO]: [TARDIS] TARDIS version: 5.7.5-b3006
[20:56:36 INFO]: [TARDIS] Vault version: 1.7.3-b131
[20:56:36 INFO]: [TARDIS] PlaceholderAPI version: 2.11.6
[20:56:36 INFO]: [TARDIS] WorldGuard version: 7.0.12+829a4a4
[20:56:36 INFO]: [TARDIS] Multiverse-Core version: 4.3.1-b861
[20:56:36 INFO]: [TARDIS] GriefPrevention version: 16.18.4
[20:56:36 INFO]: [TARDIS] Essentials version: 2.21.0-dev+121-f7a8f86
[20:56:36 INFO]: [TARDIS] LibsDisguises version: 10.0.44-SNAPSHOT

**Comment by Insomniac314** [comment]
Heres another part of the exception sequence
[20:50:15 WARN]: [TARDIS] Task #5811 for TARDIS v5.7.5-b3006 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.target" is null
        at TARDIS.jar/me.eccentric_nz.TARDIS.flight.TARDISManualFlightRunnable.run(TARDISManualFlightRunnable.java:65) ~[TARDIS.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:50:19 WARN]: [TARDIS] Task #5811 for TARDIS v5.7.5-b3006 generated an exception
java.lang.NullPointerException: Cannot invoke "me.eccentric_nz.TARDIS.builders.BuildData.getLocation()" because "bd" is null
        at TARDIS.jar/me.eccentric_nz.TARDIS.flight.TARDISFlightAdjustment.getLocation(TARDISFlightAdjustment.java:52) ~[TARDIS.jar:?]
        at TARDIS.jar/me.eccentric_nz.TARDIS.flight.TARDISManualFlightRunnable.run(TARDISManualFlightRunnable.java:82) ~[TARDIS.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by eccentricdevotion** [comment]
Can't reproduce, I have RUSTIC console and manual flight doesn't throw any errors
Attach TARDIS.db...

**Comment by Insomniac314** [comment]
[TardisDBFile924.zip](https://github.com/user-attachments/files/17599562/TardisDBFile924.zip)

**Comment by eccentricdevotion** [comment]
Database contains the needed records so I don't know why you are getting an error.
Have you tried the new build?
