### ISSUE TITLE
Plugin does not enable on startup

### ISSUE THREAD

**Issue by Insomniac314** [eccentricdevotion/TARDIS#928]
### Describe the bug

Plugin throws exception on startup.

### To Reproduce

Install plugin
Start the server

### Log files

[20:29:57 ERROR]: Error occurred while enabling TARDIS v5.8.0-b3012 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/managers/storage/StorageException
        at TARDIS.jar/me.eccentric_nz.TARDIS.TARDIS.loadWorldGuard(TARDIS.java:1538) ~[TARDIS.jar:?]
        at TARDIS.jar/me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:384) ~[TARDIS.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-15-99f4bb2]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.managers.storage.StorageException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 14 more
### '/tardis version' output

Unable to retrieve info

**Comment by Insomniac314** [comment]
tried 1.21.3 build as well but nothing

**Comment by eccentricdevotion** [comment]
You are running a 1.21.3 build (v5.8.0) on 1.21.1, update Spigot/Paper

**Comment by eccentricdevotion** [comment]
Build 3010 is the last for 1.21.1

**Comment by eccentricdevotion** [comment]
These work:
https://ci.enginehub.org/repository/download/bt10/25594:id/worldedit-bukkit-7.3.9-SNAPSHOT-dist.jar?branch=version/7.3.x&guest=1
https://ci.enginehub.org/repository/download/bt11/25574:id/worldguard-bukkit-7.0.13-SNAPSHOT-dist.jar?branch=version/7.0.x&guest=1
