### ISSUE TITLE
/tardis find not working

### ISSUE THREAD

**Issue by gomalley411** [eccentricdevotion/TARDIS#94]
For whatever reason when I teleport to the coordinates listed under /tardis find there is no TARDIS there...

**Comment by eccentricdevotion** [comment]
**Log files**
Paste your server log on a website like pastebin.com, and post a link here.

**Comment by gomalley411** [comment]
`[14:28:34] [Server thread/INFO]: Gommeh is a Death Eater

[14:28:34] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TARDIS v4.0.5-b1799

java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;

at me.eccentric_nz.TARDIS.utility.TARDISWorldGuardUtils.updateRegionForNameChange(TARDISWorldGuardUtils.java:386) ~[?:?]

at me.eccentric_nz.TARDIS.listeners.TARDISJoinListener.onJoin(TARDISJoinListener.java:165) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor516.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-506]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-506]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-506]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:262) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1124) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-506]

at java.lang.Thread.run(Thread.java:834) [?:?]

[14:28:34] [Server thread/INFO]: Gommeh[/192.160.165.63:64101] logged in with entity id 682008 at ([flatlands]108032.5, 50.0, 99204.5)

[14:28:34] [Server thread/INFO]: BigBadBakerson issued server command: /replacenear 100 dirt diamond_block

[14:28:38] [Server thread/INFO]: Medaris issued server command: //set 98

[14:28:38] [Server thread/INFO]: BigBadBakerson issued server command: /replacenear 10 dirt diamond_block

[14:28:38] [Server thread/INFO]: Dannnoe issued server command: /disguise Thrown_Exp_Bottle

[14:28:42] [Server thread/INFO]: Gommeh issued server command: /tardis find

[14:28:50] [Server thread/INFO]: Dannnoe issued server command: /tp Dannnoe RideWithMinaj

[14:28:52] [Server thread/INFO]: BigBadBakerson issued server command: //set 0

[14:28:53] [User Authenticator #54/INFO]: UUID of player brandonkeith is 6120f97b-9cee-3770-9524-3abf98b0ee21

[14:28:53] [Server thread/INFO]: brandonkeith[/68.101.92.246:51498] logged in with entity id 682018 at ([flatlands]-5724.352831328675, 86.73557223362799, 3122.67657425041)

[14:28:55] [Server thread/INFO]: Dannnoe issued server command: /disguise Arrow

[14:28:55] [Server thread/INFO]: < AaronPTB> what happened to the spawn

[14:28:56] [Server thread/INFO]: Gommeh issued server command: /tppos 108032 50 99204

[14:29:00] [Server thread/INFO]: Amickey issued server command: /potion clear

[14:29:00] [Server thread/INFO]: Bad Bitchhh < !!Barbie!!> Bruh stop

[14:29:02] [Server thread/INFO]: Gommeh issued server command: /logs

[14:29:07] [Server thread/WARN]: [TARDIS] Task #58 for TARDIS v4.0.5-b1799 generated an exception

java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;

at me.eccentric_nz.TARDIS.utility.TARDISWorldGuardUtils.mobsCanSpawnAtLocation(TARDISWorldGuardUtils.java:534) ~[?:?]

at me.eccentric_nz.TARDIS.move.TARDISMonsterRunnable.canSpawn(TARDISMonsterRunnable.java:228) ~[?:?]

at me.eccentric_nz.TARDIS.move.TARDISMonsterRunnable.run(TARDISMonsterRunnable.java:196) ~[?:?]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-506]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-506]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-506]

at java.lang.Thread.run(Thread.java:834) [?:?]

`

**Comment by gomalley411** [comment]
https://pastebin.com/S6kYMmjG

**Comment by eccentricdevotion** [comment]
Wrong version of WorldGuard/WorldEdit update to latest builds - http://www.enginehub.org

**Comment by gomalley411** [comment]
I don't have access to that (cause I'm not high enough in rank on that server). Is there anything I can do ingame to destroy my Tardis without being in it?

**Comment by eccentricdevotion** [comment]
Probably get similar errors if you tried to destroy it.
